### ISSUE TITLE
Invalid Syntax when trying to start

### ISSUE THREAD

**Issue by dustinbaxa** [nabeel-oz/qlik-py-tools#103]
**Describe the bug**
When trying to start Qlik-Py-Start.bat, I get an invalid syntax error so it never fully starts. I ran through the installer and everything appears to be installed correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/20605019/83894263-0fda2200-a71f-11ea-8726-c91b937f71b9.png)

**Environment:**
Windows Server 2012 R2
Qlik Sense April 2020 R1

**Additional context**

**Comment by nabeel-oz** [comment]
Hi @dustinbaxa , that looks like valid syntax in Python 3.6. Can you check if you have a different version of Python installed? 

You can confirm by opening a Command Prompt or PowerShell window and typing `Python`.

**Comment by dustinbaxa** [comment]
Hi @nabeel-oz , OK, so it was a 3.5.x version of Python so I have updated to 3.6.8. Now, when I run Qlik-Py-Start.bat I get a "Python has stopped working" error, which in the CMD mentions a missing module called 'encodings'?

![image](https://user-images.githubusercontent.com/20605019/84418417-2da6fb80-abe5-11ea-8e84-44a8b284bb1e.png)

**Comment by dustinbaxa** [comment]
@nabeel-oz - I went ahead and deleted the folder qlik-py-env and reran the Qlik-Py-Init.bat and now everything is running! Thanks!
