### ISSUE TITLE
Qlik SSE is not running in April 2020 release 

### ISSUE THREAD

**Issue by ahmedkhancgt** [nabeel-oz/qlik-py-tools#106]
**Function**
'PyTools.sklearn_Setup'

**Describe the bug**
'PyTools.sklearn_Setup' is not a registered SSE function. Ensure the plugin is running and try restarting Qlik Engine.

**Full error message from Python**
Provide full stack trace for the error.
If using `Qlik-Py-Start` you can provide screenshots from the terminal. Make sure to go all the way up to the start of the errors.
Alternatively, you can provide the latest log files from `../qlik-py-tools/qlik-py-env/core/logs`.

**Error message in Qlik**
[Result-Setup]:
    LOAD
        model_name,
        result,
        timestamp
    EXTENSION PyTools.sklearn_Setup(MODEL_INIT{Model_Name, EstimatorArgs, ScalerArgs, ExecutionArgs})

**Expression or load script used in Qlik**
Provide a screenshot of the expression or load script where the SSE is being used in Qlik.

**Environment:**
 - OS [e.g. Windows Server, Linux]
windows 10

 - Qlik Sense Enterprise/ Desktop/ Kubernetes/ QlikView
 Qlik sense desktop

- SSE Version
SSE 7

**Additional context**

**Comment by nabeel-oz** [comment]
Hi @ahmedkhancgt , the error indicates that the Qlik Sense Engine has not detected the SSE. You'll need to check through the [installation notes](https://github.com/nabeel-oz/qlik-py-tools#installation) from step 4 onwards and see if something was missed. 

For Qlik Sense Desktop take a look at the solution for issue #63.
