### ISSUE TITLE
DLL Load Failed error

### ISSUE THREAD

**Issue by Nitsqlik** [nabeel-oz/qlik-py-tools#14]
While running the Qlik-py-Start.bat file, I am facing" Import Error: DLL Load failed: The specified procedure could not be found. 
And when I try to run in qliksense, error pops up "PyTool.sklearn_Setup is not a registered SSE function. Ensure the plugin is running"

**Comment by Nitsqlik** [comment]
Qliksense App I am trying to open is "Sample-App-scikit-learn-Train-Test.qvf"

**Comment by nabeel-oz** [comment]
Hi @Nitsqlik , did you finish all the [installation steps](https://github.com/nabeel-oz/qlik-py-tools#installation) successfully? The error means that the SSE can't start due to some failure in the initialization process.

**Comment by nabeel-oz** [comment]
Also, you may want to check that the SSE name used in the app matches the name you used for the analytics connection (step 6 under installation). Your message shows 'PyTool' instead of the default 'PyTools' used in the examples.
