### ISSUE TITLE
Using Qliksense June 2018 Enterprise

### ISSUE THREAD

**Issue by cyonghui81** [nabeel-oz/qlik-py-tools#15]
Hi, I would like to ask if I can use the June 2018 Enterprise version for Prophet as that is the only version that we have

**Comment by nabeel-oz** [comment]
Hi @cyonghui81, June 2018 does support Analytic Connections so this SSE should work with the version. However I have used more recent features including bundled extensions in the demo apps. The SSE protocol has also been improved over newer versions.

**Comment by cyonghui81** [comment]
Thanks for the fast response ! Appreciated. There is another question i like to ask, where do i get the source data for the sample apps, e.g. VIC Emergency Department Attendances.xlsx

**Comment by nabeel-oz** [comment]
Hi @cyonghui81 , apologies for the delay. I was off on vacation.

The data sources are cited under the Attribution section in the usage documentation. The VIC Emergency Department Attendances data was obtained from [Victorian Health Services Performance](http://performance.health.vic.gov.au/Home/Report.aspx?ReportKey=157).

I have attached the source data files in the apps to make them more portable for Qlik Sense Enterprise.
