### ISSUE TITLE
Error execute prophet function

### ISSUE THREAD

**Issue by MarcoBIConsultant** [nabeel-oz/qlik-py-tools#16]
Hello, i try the package and when i use prophet function sometimes i receive a message error in chart. I see the logs into the package and i find which the python function not receive the input value but when I change something in the chart (for example sorting type, it reload and return the chart value).

I think which Qlik execute the prophet function in the chart above to send the value to python ( even when I apply a filter).

What can I do?

Thank you

Marco

**Comment by nabeel-oz** [comment]
Hi Marco, do you have this problem with the sample apps as well? Just wondering if there is something special about your data or chart settings. 

Qlik will trigger the call to Python on any action that affects that chart. So when you navigate to the sheet or make a selection, let the chart load before you do anything else. I've used buttons in the sample apps to enable or disable the forecasting to provide a better user experience.

Apologies on the late reply. I just got back from leave.

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz , thank you for answer.
My problem is when i apply a filter in my sheet (you can see the attached in this message).
The expression is the same as your example only difference is the debug parameter to true:
PyTools.Prophet(MonthYear, Sum(Sales) , 'freq=MS, return=yhat, debug=true')

MonthYear is Dual(Year(DATE) & '-' & Month(DATE), MonthStart(DATE)) is the calendar table in the load script where is linked in Sales table with IDDate

Can you help me to understand the problem?
Thank you

Marco


![Immagine](https://user-images.githubusercontent.com/48477504/54668358-fd120800-4aee-11e9-8ede-be8297bcfdc9.png)

**Comment by nabeel-oz** [comment]
Hi Marco, if the forecast doesn't work after applying filters it might indicate a problem with the the granularity of future periods. Do you have future dates that are associated to the selections? If you don't the forecast will fail as there is nothing to be predicted.

I have approached this problem by building a separate forecast calendar that works with selections in any field. There is a reusable script and instructions available in the usage documentation [here](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app).

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz , yes in my script there is the calendar with future date in cross join with the dimensions.
The strange thing is if i change order measures ( order number or order by expression) in the chart, it updates and the prediction appears.
Why?

Thank you
Marco

**Comment by nabeel-oz** [comment]
Hi Marco, if you're using the forecast calendar like in the sample app, you should have a bit of set analysis for your measure to pass correct values:

```
PyTools.Prophet(MonthYear, Sum({$<FORECAST_LINK_TYPE = {'Actual'}>}  Sales) , 'freq=MS, return=yhat, debug=true')
```

I can't replicate your exact issue with my apps, so if you can send me an app with sample data I could dig a bit deeper.

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz i try if condition in the measure if('$(vPausePredictions)' <> 'pause', Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct ACCIDENT_NO) and maybe it works

**Comment by nabeel-oz** [comment]
Thanks great. Glad we could get it working.
