### ISSUE TITLE
Possible VC++ MSVC issues for fbprohphet

### ISSUE THREAD

**Issue by Paarthos** [nabeel-oz/qlik-py-tools#17]
Hi Nabeel,

I tried installing the SSE desktop version as per the instructions on 2 different windows 10 machines but failed to install fbprophet on both of them.
On researching I found that pystan has issues with the MSVC Lib files and there is very less support on the issue.  

Can I use any other C++ compilers? Can you please point to the version compatible with all the packages?

Best,
Paarth Sanghavi

**Comment by nabeel-oz** [comment]
Hi Paarth, the MS Visual Studio 2017 Build Tools work fine with pystan 2.17 on Windows 10. I've set the initialization script to use this version of pystan. 

Did you select the C++ compilers in the optional components as shown in the [installation section](https://github.com/nabeel-oz/qlik-py-tools#installation).

![image](https://user-images.githubusercontent.com/21298843/54657510-cef7ec80-4b1d-11e9-8c0d-bda25d47401b.png)

If you're still getting the error can you paste the text from the command prompt here.

Apologies for the slow response. I just got back from a vacation.

**Comment by Paarthos** [comment]
Hi Nabeel,

Yes, I followed the steps. Here's the issue I am facing.

**Comment by Paarthos** [comment]
Hi Nabeel,

Thanks for your reply.

I followed the steps. Here's the issue I am facing.

LINK : fatal error LNK1104: cannot open file 'kernel32.lib'
error: command 'C:\\Program Files (x86)\\Microsoft Visual
Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe'
failed with exit status 1104

kernel32.lib is in the \\Windows Kits\10\Lib\10.0.17134.0\um\x86 and I have
it in my account variables but the qlik.init.bat isn't picking it up.

Please advice.

Best,
Paarth Sanghavi

**Comment by nabeel-oz** [comment]
Hi Paarth,

To me this looks like a problem with your Visual Studio installation. Are you sure you have the VS Build Tools installed? The path in the error message is pointing to VS Community which you may be using for other things, but for the Python packages used in this project we need the components that come with the Build Tools. 

If you did install the VS Build Tools previously you may want to uninstall and try again, making sure you choose all the optional components shown above. 

https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

**Comment by nabeel-oz** [comment]
Closing this issue as it looks like an environment issue in installing MS Visual Studio Build Tools.
