### ISSUE TITLE
'python' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by lalprasanth** [nabeel-oz/qlik-py-tools#18]
![Screenshot (42)](https://user-images.githubusercontent.com/48248322/55469662-91b65300-5623-11e9-8ac0-8fa9d932e1a1.png)

I am getting python is not recognised as an internal or external command. can you please tell me, what is the issue I am going through?

**Comment by nabeel-oz** [comment]
That means Python has not been installed correctly on your system. When installing Python you also need to make sure you select the option to update the PATH environment variable.

**Comment by lalprasanth** [comment]
it worked, appreciate your advice.

**Comment by lalprasanth** [comment]
![7part](https://user-images.githubusercontent.com/48248322/55547457-f38fbf00-56ee-11e9-84b9-0af37cc06443.JPG)
Hi Nabeel,
     I couldn't see this part running when restarted the Qlik Sence desktop. Can you please tell me where I am doing it wrong but I am sure I've done the rest of the part.

**Comment by lalprasanth** [comment]
it's working. My bad, I didn't run Qlik-Py-Init.bot. Thanks

**Comment by nabeel-oz** [comment]
Great. Glad you got it working.
