### ISSUE TITLE
How to start PyTools when start my server (windows)??

### ISSUE THREAD

**Issue by EderBuug** [nabeel-oz/qlik-py-tools#19]

**Comment by ibarrond** [comment]
Best way might be by creating a batch (.bat) file in Windows that contains the same info as `Qlik-Py-Start.bat` and then launches Qlik Sense / other.

**Comment by nabeel-oz** [comment]
As mentioned by @ibarrond the commands to start PyTools are in the `Qlik-Py-Start.bat` file. You can schedule this batch file to run on startup using the Windows Task Scheduler or run it as a service using a third party tool such as NSSM.
