### ISSUE TITLE
visualization was not found on the server

### ISSUE THREAD

**Issue by lalprasanth** [nabeel-oz/qlik-py-tools#20]
![Invalid visulaisation](https://user-images.githubusercontent.com/48248322/55706380-b7b26d80-59fe-11e9-90e2-c3185233b18b.JPG)

Hi Nabeel,

   Hope you're doing fine. I am facing an issue as it is in the above image, for now, I am running this in the desktop. May I know what is the issue I am going through?

**Comment by nabeel-oz** [comment]
Hi @lalprasanth , that's the standard Qlik Sense message when you are missing a visualization extension. In this case you need to install the Dashboard Extension Bundle that comes as an optional component with Qlik Sense November 2018 or later.

**Comment by lalprasanth** [comment]
It worked. Appreciated, thanks for your help.
