### ISSUE TITLE
Forecast Calendar with (Standar) Master Calendar of Qlik

### ISSUE THREAD

**Issue by EderBuug** [nabeel-oz/qlik-py-tools#21]
Hi:
I have created my application environment under the Qlik standard 'Master Calendar', I have tried to modify the Master calendar to work with 'Forecast Calendar', but I haven't succeeded. How can I join 'Master Calendar' with 'Forecast Calendar'?
How to make them work together?

**Comment by nabeel-oz** [comment]
Hi @EderBuug , the Forecast Calendar should be linked to the key date in your fact table via the Actual to Forecast Link table as shown in the [usage documentation](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app). This shouldn't affect your master calendar as it would be a separate table with different field names except the key date field.

**Comment by EderBuug** [comment]
@nabeel-oz Thanks, issue solved :D
