### ISSUE TITLE
qlik with Python for Machine Learning

### ISSUE THREAD

**Issue by subash28kumar** [nabeel-oz/qlik-py-tools#23]
Hi Nabeel,

I am trying to integrate the Python with Qlik sense desktop with the steps you have mentioned in the Github (https://github.com/nabeel-oz/qlik-py-...)
After installing the required prerequisites (Python 3.6 version, Qlik Desktop and Microsoft Visual C++ Build Tools), I am still facing the below issue, after I execute the Qlik-Py-Init.bat, windows.bat file

1.  "error: Command "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\skumar\appdata\local\temp\temp5_qlik-py-tools-4.0.zip\qlik-py-tools-4.0\qlik-py-env\include -IC:\Users\skumar\AppData\Local\Programs\Python\Python37\include -IC:\Users\skumar\AppData\Local\Programs\Python\Python37\include -IC:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\include -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt /EHsc /Tppystan/_misc.cpp /Fobuild\temp.win-amd64-3.7\Release\pystan/_misc.obj" failed with exit status 2"

2. "Command "c:\users\skumar\appdata\local\temp\temp5_qlik-py-tools-4.0.zip\qlik-py-tools-4.0\qlik-py-env\scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\skumar\\AppData\\Local\\Temp\\pip-install-9fy4r3pa\\pystan\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\skumar\AppData\Local\Temp\pip-record-1qbg_m01\install-record.txt --single-version-externally-managed --compile --install-headers c:\users\skumar\appdata\local\temp\temp5_qlik-py-tools-4.0.zip\qlik-py-tools-4.0\qlik-py-env\include\site\python3.7\pystan" failed with error code 1 in C:\Users\skumar\AppData\Local\Temp\pip-install-9fy4r3pa\pystan\"

Please suggest any solution, if you could help me out on this!!
Thank you so much for the support and great work
Regards
Subash Kumar
nivi05subhash@gmail.com

**Comment by HeinRique** [comment]
Hi Subash, 

The second one is about a gcc error to compile pystan.  In documentation page from the pystan module, there is a workaround for this problem. For me, using Anaconda, I just type:
`conda install pystan -c conda-forge`

Besides that, you mentioned that you're using Python 3.6 but your log error says _**python3.7**_

> --compile --install-headers c:\users\skumar\appdata\local\temp\temp5_qlik-py-tools-4.0.zip\qlik-py-tools-4.0\qlik-py-env\include\site\python3.7\pystan" failed 

Check if are any problems with your envs.

Regards

**Comment by nabeel-oz** [comment]
Thanks for your contribution @HeinRique !

@subash28kumar As mentioned above the error shows that you're using Python 3.7, which is not yet supported by all the libraries used in this project. You will need to uninstall your current version of Python and install 3.6.8 to be able to use PyTools.

https://www.python.org/downloads/release/python-368/

**Comment by subash28kumar** [comment]
Hi Nabeel/Hein
I am still seeing this error, while trying to uninstall the 3.7 and installing 3.6.8 python

Installing collected packages: pystan
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\users\\skumar\\appdata\\local\\temp\\temp6_qlik-py-tools-4.0.zip\\qlik-py-tools-4.0\\qlik-py-env\\Lib\\site-packages\\pystan\\stan\\src\\test\\test-models\\good\\function-signatures\\distributions\\univariate\\continuous\\scaled_inv_chi_square\\scaled_inv_chi_square_ccdf_log.stan'

Any thoughts on this

Regards
Subash Kumar

**Comment by subash28kumar** [comment]
Hi Nabeel/Hein,

We are able to integrate the Python with Qlik Sense based on your instruction,

Now am trying to bring the pandas and numpy  python modules into the qlik
I just added the pandas in the Qlik-Py-Init batch file and started the Qlik-py-Start batch file, is it something correct approach

I am still not able to see pandas and numpy modules in qlik

Thank you so much for your input, really interesting and helpful

regards
Subash Kumar

**Comment by nabeel-oz** [comment]
I think you may have misunderstood the capabilities of this Server Side Extension (SSE). It provides functions built in Python which provide a specific capability to be used in Qlik. For e.g the Prophet function can produce a forecast. There is Python code behind the function that uses several libraries like fbprophet, pandas and numpy, but in Qlik you simply call the function in the expression editor or load script to produce a forecast without having to use any Python code.

It is possible to write Python script in Qlik and have it evaluated in the SSE, but this type of usage is not available with PyTools as mentioned in the [notes on the approach](https://github.com/nabeel-oz/qlik-py-tools#note-on-the-approach). 

If you want to build your own SSE the best place to start is here: https://github.com/qlik-oss/server-side-extension

**Comment by subash28kumar** [comment]
Thank you so much Nabeel for the explanation, I am trying to bring the pandas and numpy libraries into qlik, but not sure how to start in github

Regards
Subash Kumar

**Comment by subash28kumar** [comment]
Hi Nabeel,

I am just trying to setup the model with the below load script

[In]:
LOAD
    Model_Name,
    EstimatorArgs,
    ScalerArgs,
    ExecutorArgs
FROM [lib://qlik py testing/MODEL_INIT.xlsx]
(ooxml, embedded labels, table is MODEL_INIT);

[out]:
LOAD
    Model_Name,
    EstimatorArgs,
    ScalerArgs,
    ExecutorArgs
EXTENSION PythonTools.sklearn_Setup(In{Model_Name,EstimatorArgs,ScalerArgs,ExecutorArgs});

I am getting below error:
Started loading data
In << MODEL_INIT
Lines fetched: 1
The following error occurred:
Connector reply error: grpc::StatusCode::UNKNOWN: 'Exception iterating responses: dictionary update sequence element #0 has length 1; 2 is required'
The error occurred here:

Data has not been loaded. Please correct the error and try loading again.

Apologize if disturbing again

regards
Subash Kumar

**Comment by nabeel-oz** [comment]
The arguments you are passing are probably not in the required syntax. Check them against the documentation to be sure you are providing the correct keywords and separators.

**Comment by subash28kumar** [comment]
Hi Nabeel,

Thank you for the response, just wanted to check with you on the Prophet function for forecasting, with below syntax, we tried connecting sample superstore data in qlik and tried to forecast the values based on ship date on monthly frequency), the formula is working but unable to see any predicted line
PyTools.Prophet([Ship Date],Sum(Profit),'freq=M')

Thank you for all your support and help

regards
Subash Kumar

**Comment by nabeel-oz** [comment]
Please look at the [usage documentation](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app) for applying the function correctly. The expression looks ok but your app may miss some essential requirement such as passing the future periods to the SSE.

**Comment by subash28kumar** [comment]
Hi Nabeel,

Thank you so much for your guidance, still I am not able to plot the prediction chart in qlik

Apologize, I am new to qlik and I am troubling you again and again, sorry for that. If you could help me on this, this would be really helpful.

1. Tried creating a new app having guidance of your app while data loading, 
2. We do not see any issues while doing data loading, but while ploting the chart with required dimensions and measures, unable to see chart
Dimensions: Order_date
Add Measures: Sum(Sales)
Add Measures: PyTools.Prophet(if(FORECAST_MONTH <= AddMonths(Max(Total [Order Month & Year]), $(vforecastperiod)), FORECAST_MONTH),

Also tried Dimensions: =if(FORECAST_MONTH <= AddMonths(Max(Total [Order Month & Year]), $(vforecastperiod)), FORECAST_MONTH)
Measures: Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct 'Order ID')
Add Measures: PyTools.Prophet(if(FORECAST_MONTH <= AddMonths(Max(Total [Order Month & Year]), $(vforecastperiod)), FORECAST_MONTH),
				Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct [Order ID]),
                'freq=MS, return=yhat')
				Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct [Order ID]),
                'freq=MS, return=yhat')

if you can share me your email id, I could share the qvf app I created in qlik.

Regards
Subash Kumar
9046147652

**Comment by subash28kumar** [comment]
Hi Nabeel,

I feel the app is working with  future forecast dates are being passed to the SSE correctly, because I am able to view the future and historic dates based on the current date in the layout. 
The [Date Column] is extend into the future to cover the periods you want to forecast

Report frontend layout:
Dimension: =if(FORECAST_MONTH <= AddMonths(Max(Total [Order_Date]), $(vforecastperiod)),FORECAST_DATE)
Measures=PyTools.Prophet(FORECAST_MONTH,sum(Sales),'freq=M')

load script:
// Here we set the maximum number of years to be forecasted
SET vMaxForecastYears = 5;

// We then get the minimum and maximum dates in the key date field
[TempDateMinMax]:
LOAD
	min([Order_Date]) as minDate,
    max([Order_Date]) as maxDate
    //sum([Sales]) as Sales
RESIDENT [Orders];

// We store the minimum date as a variable. This will be the start date for our forecast calendar
LET vCalendarStartDate = Peek('minDate', 0, 'TempDateMinMax');
// We also store the start date for the forecasting (the first 'future' date). No historical data exists from this date onwards
LET vForecastStartDate = Peek('maxDate', 0, 'TempDateMinMax')+1;
// Finally store the the last date for the forecast
LET vForecastEndDate = $(vForecastStartDate) + 365 * $(vMaxForecastYears);

// Now that we have the variables the temp table can be dropped
drop table TempDateMinMax;

// Create a calendar from the earliest date in the data to the maximum forecast date
// Read from the third load statement below to the top as this is a preceding load
[Forecast Calendar]:
LOAD
	FORECAST_DATE,
    FORECAST_MONTH,
    FORECAST_YEAR,
    FORECAST_DATE_TYPE,
    '<ALL>' as FORECAST_KEY;

// Create month and year fields as well as a field to tell us if the date is historic or in the future:
LOAD
	FORECAST_DATE,
    Dual(Year([FORECAST_DATE]) & '-' & Month([FORECAST_DATE]), MonthStart([FORECAST_DATE])) as FORECAST_MONTH,
    Year([FORECAST_DATE]) as FORECAST_YEAR,
    if(FORECAST_DATE < $(vForecastStartDate), 'Historic', 'Future') as FORECAST_DATE_TYPE;

// Autogenerate dates for the required range:
LOAD  
  	Date($(vCalendarStartDate) + IterNo() - 1) as FORECAST_DATE  
AutoGenerate 1 
While $(vCalendarStartDate) + IterNo() - 1 <= $(vForecastEndDate);

// Notice the <ALL> in the load above. In our first run we create a generic key that will link each date in the forecast calendar to all actual dates.
// In the load below, we create a copy of the data in the Forecast Calendar where the key is the actual Date
// This will help us separate selections on actual dates/ months/ years with forecast dates and avoid gaps in our forecasting.
Concatenate([Forecast Calendar])
LOAD
	FORECAST_DATE,
    FORECAST_MONTH,
    FORECAST_YEAR,
    FORECAST_DATE_TYPE,
    FORECAST_DATE as FORECAST_KEY
RESIDENT [Forecast Calendar];

// The values to be forecasted are linked to the forecast calendar by the key date
[Actual to Forecast Link]:
LOAD DISTINCT
	Order_Date,
    'Actual' as FORECAST_LINK_TYPE,
    Order_Date as FORECAST_KEY
    //Sales
RESIDENT Orders;

// Each key date is also linked to all possible dates in the forecast calendar
// This is to allow the timeseries to be plotted without any gaps
Concatenate([Actual to Forecast Link])
LOAD DISTINCT
	Order_Date,
    'Generic' as FORECAST_LINK_TYPE,
    '<ALL>' as FORECAST_KEY
    //Sales
RESIDENT Orders;

Not sure though, what I am missing from the above code, once I add the Pytool.Prophet(FORECAST_MONTH, sum(Sales),'freq=M') to the measures in the front end layout in the app, I am seeing the error "The Service is currently unavailable.You may be able to correct this by retrying and using backoff"

Thought to check with you, if anything I am missing 

Thank you for the support 

Regards
Subash K

**Comment by nabeel-oz** [comment]
Hi Subash, in your latest post you're using FORECAST_DATE as the dimension, yet using FORECAST_MONTH in the measure. That is incorrect as the granularity of the data should match.

Also, if the error mentions the service not being available, you need to confirm that the connection to the SSE is working.

You can attach files to issues in GitHub so if your app can be shared publicly you can post it here.

**Comment by subash28kumar** [comment]
Hi Nabeel, thank you for the swift response, sorry for the wrong granularity, I have changed the Dimension from FORECAST_DATE to FORECAST_MONTH, I ran the batch files and restart the connection to SSE again, now am not seeing service not available error, but still after the adding the measure as PyTools.Prophet(FORECAST_MONTH,sum(Sales),'freq=M'), unable to see any values, it is showing blank, attached the screenshot below

![prophet](https://user-images.githubusercontent.com/49568152/57271309-ff0f3680-705c-11e9-90ad-8f6d4f1d5127.PNG)

Dimension: =if(FORECAST_MONTH <= AddMonths(Max(Total [Order_Date]), $(vforecastperiod)),FORECAST_MONTH)

Measure: PyTools.Prophet(FORECAST_MONTH,sum(Sales),'freq=M')

Data load script:
[Orders]:    
LOAD
    "Row ID",
    "Order ID",
    "Order_Date",
    "Ship Date",
    "Ship Mode",
    "Customer ID",
    "Customer Name",
    Segment,
    Country,
    City,
    State,
    "Postal Code",
    Region,
    "Product ID",
    Category,
    "Sub-Category",
    "Product Name",
    "Sales",
    Quantity,
    Discount,
    Profit
FROM [lib://sample/Sample - Superstore.xls]
(biff, embedded labels, table is Orders$);


// Here we set the maximum number of years to be forecasted
SET vMaxForecastYears = 5;

// We then get the minimum and maximum dates in the key date field
[TempDateMinMax]:
LOAD
	min([Order_Date]) as minDate,
    max([Order_Date]) as maxDate
    //sum([Sales]) as Sales
RESIDENT [Orders];

// We store the minimum date as a variable. This will be the start date for our forecast calendar
LET vCalendarStartDate = Peek('minDate', 0, 'TempDateMinMax');
// We also store the start date for the forecasting (the first 'future' date). No historical data exists from this date onwards
LET vForecastStartDate = Peek('maxDate', 0, 'TempDateMinMax')+1;
// Finally store the the last date for the forecast
LET vForecastEndDate = $(vForecastStartDate) + 365 * $(vMaxForecastYears);

// Now that we have the variables the temp table can be dropped
drop table TempDateMinMax;

// Create a calendar from the earliest date in the data to the maximum forecast date
// Read from the third load statement below to the top as this is a preceding load
[Forecast Calendar]:
LOAD
	FORECAST_DATE,
    FORECAST_MONTH,
    FORECAST_YEAR,
    FORECAST_DATE_TYPE,
    '<ALL>' as FORECAST_KEY;

// Create month and year fields as well as a field to tell us if the date is historic or in the future:
LOAD
	FORECAST_DATE,
    Dual(Year([FORECAST_DATE]) & '-' & Month([FORECAST_DATE]), MonthStart([FORECAST_DATE])) as FORECAST_MONTH,
    Year([FORECAST_DATE]) as FORECAST_YEAR,
    if(FORECAST_DATE < $(vForecastStartDate), 'Historic', 'Future') as FORECAST_DATE_TYPE;

// Autogenerate dates for the required range:
LOAD  
  	Date($(vCalendarStartDate) + IterNo() - 1) as FORECAST_DATE  
AutoGenerate 1 
While $(vCalendarStartDate) + IterNo() - 1 <= $(vForecastEndDate);

// Notice the <ALL> in the load above. In our first run we create a generic key that will link each date in the forecast calendar to all actual dates.
// In the load below, we create a copy of the data in the Forecast Calendar where the key is the actual Date
// This will help us separate selections on actual dates/ months/ years with forecast dates and avoid gaps in our forecasting.
Concatenate([Forecast Calendar])
LOAD
	FORECAST_DATE,
    FORECAST_MONTH,
    FORECAST_YEAR,
    FORECAST_DATE_TYPE,
    FORECAST_DATE as FORECAST_KEY
RESIDENT [Forecast Calendar];

// The values to be forecasted are linked to the forecast calendar by the key date
[Actual to Forecast Link]:
LOAD DISTINCT
	Order_Date,
    'Actual' as FORECAST_LINK_TYPE,
    Order_Date as FORECAST_KEY
    //Sales
RESIDENT Orders;

// Each key date is also linked to all possible dates in the forecast calendar
// This is to allow the timeseries to be plotted without any gaps
Concatenate([Actual to Forecast Link])
LOAD DISTINCT
	Order_Date,
    'Generic' as FORECAST_LINK_TYPE,
    '<ALL>' as FORECAST_KEY
    //Sales
RESIDENT Orders;

Regards
Subash Kumar
nivi05subhash@gmail.com

**Comment by subash28kumar** [comment]
Hi Nabeel,

I am not sure how to share the app through github, that is the reason, I shared the above code for your view.
Regards
Subash Kumar

**Comment by subash28kumar** [comment]
Hi Nabeel,

I am able to plot the values, from the below uploaded image, the first 2 columns are actual date(Order date) and sum(Sales) from sample superstore data, the next 2 columns are forecasted columns using the SSE extension, but still I feel the data is not populating correct, looks like join issue, Need your thoughts, if you could help me on this.

![Prophet_Capture2](https://user-images.githubusercontent.com/49568152/57337802-d89ed900-70f8-11e9-97b9-13c2aa038def.PNG)

Regards
Subash Kumar
nivi05subhash@gmail.com
(if you feel comfortable, could you please share me your email id), please apologize, if you feel disturbing.

**Comment by nabeel-oz** [comment]
You are missing the set analysis expression described in the usage documentation: https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app

**Comment by subash28kumar** [comment]
Hi Nabeel, 

Sure Nabeel, will check as per your guidance but unable to attach the app file for your view in github, I will look into the code again and see what am missing, any idea how can I share the app in github, tried to drag and drop the app, it populates that we don't support the file type

please confirm, what should be my dimension, is that I have to add Order_date which is the original column from the input shet or I should have the forecast date which is derived in qlik as dimension,
similarly measures will be sum(sales) from the original input sheet and I have to add one more measure with pytool library as the forecasted measure.

regards
Subash K

**Comment by subash28kumar** [comment]
Hi Nabeel,

I am able to do forecasting  now based on different frequencies I am trying to implement logistic regression, any thoughts which documentation I would need to refer now from SSE
Thank you so much for your guidance
Regards
Subash Kumar

**Comment by nabeel-oz** [comment]
You would need to refer to the machine learning section of the usage documentation.
https://github.com/nabeel-oz/qlik-py-tools#usage

I'm closing this issue as all questions have been addressed.
