### ISSUE TITLE
Integrating with qlikview

### ISSUE THREAD

**Issue by lalprasanth** [nabeel-oz/qlik-py-tools#25]
Hi Nabeel,

      
This is great, it works well with Qlik Sense. Thank you for sharing your knowledge and work with us. Coming to the point, I would like to know if this integration works with Qlikview as well?
As you know, we usually update setting.ini or analytic connection with the port number 50055 to integrate with Qlik Sense. Does this work with Qlik view as well? if I committed the same thing as I did with Qlik Sense.

**Comment by nabeel-oz** [comment]
Hi @lalprasanth, Yes analytic connections are supported from the November 2017 version of QlikView: https://help.qlik.com/en-US/qlikview/April2019/Subsystems/Client/Content/QV_QlikView/Analytic_connections.htm

**Comment by lalprasanth** [comment]
Thank you Nabeel, you've been so helpful.
