### ISSUE TITLE
Error in Qlik-Py-Start.bat in qlik-py-tools-v.4.1

### ISSUE THREAD

**Issue by MarcoBIConsultant** [nabeel-oz/qlik-py-tools#26]
Hi,
I have a error when i run the Qlik-Py-Start.bat
What can i do?

![Immagine](https://user-images.githubusercontent.com/48477504/57691640-0af28e00-7645-11e9-9387-b9af8225f00f.png)

**Comment by nabeel-oz** [comment]
It looks like hdbscan dropped a new release yesterday which has a new dependency. I'm at Qonnections this week so may not be able to get a fix in soon. But all that needs to be done is to change the init bat file to use the previous version of the hdbscan package for now. 

`pip install hdbscan==0.8.20`

**Comment by nabeel-oz** [comment]
Hi Marco,

I see that there's been another release for hdbscan today which should have fixed this issue. So you can just try running the initialisation again with PyTools 4.1.

Hdbscan issue for reference: https://github.com/scikit-learn-contrib/hdbscan/pull/298

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz , yesterday i try change hdbscan package and it is run.
After i try with new installation without change package.
I feel you.
Marco

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz , today i try new installation qlik-py-tools-v.4.1 and i have this error when i run qlik-py-start.bat


![immagine](https://user-images.githubusercontent.com/48477504/57838830-c04c4f80-77c5-11e9-8e7d-cf46bd52125e.png)

**Comment by nabeel-oz** [comment]
Hi @MarcoBIConsultant , that file is part of the SSE and is copied to the Python virtual environment during initialisation. The copy operation may fail if you ran the batch file without admin rights.

Please check that the directory `qlik-py-tools-4.1\qlik-py-env\generated` exists and contains the `ServerSideExtension_pb2.py` file. If it doesn't you can copy it from the `qlik-py-tools-4.1\generated` directory.

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz , i have use the new version and when i run the start bat file return this message:
![immagine](https://user-images.githubusercontent.com/48477504/58004816-6066e900-7ae4-11e9-8669-0e9dc33c29ef.png)

**Comment by nabeel-oz** [comment]
The fbprophet error shouldn't be a problem as we don't use plotly in this SSE. 

I have however, just published a new release which does not have this issue.
