### ISSUE TITLE
Facebook prophet forecasting not working for filters

### ISSUE THREAD

**Issue by lalprasanth** [nabeel-oz/qlik-py-tools#27]
Hi nabeel,

    
 Hope you're doing well

Basically, I worked out the forecasting model and it was successfully forecasting but the problem is that when I select the filters it's not forecasting accordingly for overtime instead it just shows the visual of the data that fed into.  

Here the first screenshot shows the forecast with no filter selection and the second one is with filter selection(also you can see that it's not predicting for the selection made). I would like to forecast for the filter selection as well, could you give me some suggestions.
![image](https://user-images.githubusercontent.com/48248322/57905991-0cff5b80-7896-11e9-9d43-3f4f1ddc3145.png)

![image](https://user-images.githubusercontent.com/48248322/57906052-41731780-7896-11e9-9714-e6ed7c0bdabf.png)

**Comment by nabeel-oz** [comment]
Hi @lalprasanth, have you set up the forecasting calendar as explained here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app

This approach allows for selections in any dimension without introducing gaps in the date dimension used for the forecast.

**Comment by lalprasanth** [comment]
Hi @nabeel-oz 
Have a look, it's connected this way but the forecasting isn't working for the filter selections. Basically, I am trying to filter fields from the warehouse table. Can you please check if I have any issues on forecast set up. 
![image](https://user-images.githubusercontent.com/48248322/58155866-6ac6e580-7c92-11e9-8e1a-c64ef386d45b.png)

**Comment by nabeel-oz** [comment]
@lalprasanth , I can't spot any obvious issue in the data model, but you may be missing the set analysis required for the measures. In the documentation and sample app we restrict `FORECAST_LINK_TYPE` to `Actual` when using a measure with dimensions from the Forecast Calendar table:

```
Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct ACCIDENT_NO)
```
This set analysis needs to be applied to the actual figures as well as to the input to Prophet:
```
PyTools.Prophet(if(FORECAST_MONTH <= AddMonths(Max(Total [Accident Month & Year]), $(vForecastPeriods)), FORECAST_MONTH),
                Count({$<FORECAST_LINK_TYPE = {'Actual'}>} Distinct ACCIDENT_NO),
                'freq=MS, return=yhat')
```

You can try creating a table object in your app and observe how the measure being used as input for the prediction changes as you apply selections. To check the data received by the SSE you can set `debug=true` in the arguments to the Prophet function. The logging information will be available in the terminal window and under  `qlik-py-tools\qlik-py-env\core\logs`.

**Comment by lalprasanth** [comment]
@nabeel-oz 
 I noticed the blank space on the following table is the reason why the filters aren't working for the forecast. The blank spaces are generated because of the auto-generated section after I load the data manager. I can see in your example where you contain everything in the load script itself that can able to forecast successfully without using the help from the data manager.
![image](https://user-images.githubusercontent.com/48248322/60715646-32762080-9f3b-11e9-8c77-de21b4be1849.png)

Year([Jour Calendaire]) AS [Jour Year],
	MonthName([Jour Calendaire]) AS [Jour Month & Year],
	Month([Jour Calendaire]) AS [Jour Month],
    Dual(Month([Jour Calendaire]) & '-' & Day([Jour Calendaire]), Num(Month([Jour Calendaire]), '00') & Num(Day([Jour Calendaire]), '00')) AS [Jour Day of Month];

the above code is the other thing I changed because I don't have to use it as how you used in your example. the one you have used is given below
   
	Year((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))) AS [Accident Year],
	MonthName((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))) AS [Accident Month & Year],
	Month((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))) AS [Accident Month],
	Dual(Month((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))) & '-' & Day((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))), Num(Month((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))), '00') & Num(Day((Date(Date#([ACCIDENTDATE], 'DD/MM/YYYY') ,'DD/MM/YYYY'))), '00')) AS [Accident Day of Month];
    
you might wonder why I am talking about this, is because I think the format of the date might have affected the table to make such blank spaces. I also tried the same way as you to contain everything in the data load script without using the data manager load but it wasn't warded off the blank space.

**Comment by nabeel-oz** [comment]
Hi @lalprasanth, using the Data Manager shouldn't be a problem as long as it is at the beginning of all your other sections built in the Data Load Editor. I have done this in the Prophet sample app as well.

The NULL values in your table indicate some association is not working as you expect in your data model, or Forecast dates have not been generated correctly. You can try commenting out parts of the `Forecast Calendar` section and see where the result is not as expected.

The end result should be that each value of `Jour Calendaire` should be linked to the same value in  `FORECAST_DATE` as well as all the historical and future dates. If you build the table below in the sample app you'll see that a single value in `Accident Date` is linked to **all** values of `FORECAST_DATE`. We can use set analysis on `FORECAST_DATE_TYPE` to identify historical or future dates, and `FORECAST_LINK_TYPE` to get dates with actual data.

![image](https://user-images.githubusercontent.com/21298843/61013888-04279380-a3c8-11e9-98a8-7bee6852af08.png)

...

![image](https://user-images.githubusercontent.com/21298843/61013898-130e4600-a3c8-11e9-8273-68baad5b928f.png)
