### ISSUE TITLE
Errors when multiple users access the app

### ISSUE THREAD

**Issue by anishazac** [nabeel-oz/qlik-py-tools#28]
Hi Nabeel,

We are getting the error when we use the prophet library extension sometimes :

ValueError: 'Series([], Name: ds, dtype: object)' is not compatible with origin='1899-12-30 00:00:00'; it must be numeric with a unit specified.

Do you know what could be the issue?

**Comment by nabeel-oz** [comment]
Hi @anishazac, the error is probably due to incorrect values or strings in the date dimension being input to the Prophet function. This field needs to be in the Qlik date data type.

**Comment by nabeel-oz** [comment]
Closing this issue as it has been inactive for 3 months.
