### ISSUE TITLE
Prophet facebook different result

### ISSUE THREAD

**Issue by MarcoBIConsultant** [nabeel-oz/qlik-py-tools#29]
Hi,
Why i have different value for same input when execute prophet facebook?
What can i do?
This are the logs for two execution.

[Prophet Log 8.txt](https://github.com/nabeel-oz/qlik-py-tools/files/3215703/Prophet.Log.8.txt)
[Prophet Log 7.txt](https://github.com/nabeel-oz/qlik-py-tools/files/3215704/Prophet.Log.7.txt)

Thank you

**Comment by nabeel-oz** [comment]
Hi @MarcoBIConsultant , the Prophet algorithm can produce some variance in the results as the model has random components. This is discussed in some posts on the prophet repository e.g. [#253](https://github.com/facebook/prophet/issues/253).

These differences are usually minor, but I see your data has very large numbers which may exaggerate the effect. I would try passing the `take_log=true` parameter or scaling the data in Qlik to a useful precision.

**Comment by shravansunkada1** [comment]
Is there any way to get reproducible results in the algorithm (by setting a random seed)?

**Comment by nabeel-oz** [comment]
The results are reproducible apart from a small degree of randomness. These variances should be minor and won't matter in most cases as the predictions come with a level of uncertainty. 

However, take a look at this discussion in issue [849](https://github.com/facebook/prophet/issues/849) on the Prophet GitHub repo. It points out some ways to reduce stochasticity of the model. I'll add a parameter for the random seed that will be applied as mentioned in that thread. 

I'm working on some other changes so this will be available with the next release.

**Comment by nabeel-oz** [comment]
Closing this issue as the questions have been addressed and changes committed.
