### ISSUE TITLE
Field 'ds' not found

### ISSUE THREAD

**Issue by olivesx** [nabeel-oz/qlik-py-tools#32]
Hi Nabeel, 

Thank you for making the PY tools available to the community. I tried performing forecasting on my own data and was prompted with "Field 'ds' not found.". I am using the latest SSE v4.4, as [per the community info](https://github.com/nabeel-oz/qlik-py-tools/issues/32)
![DS nto found](https://user-images.githubusercontent.com/46431389/59826619-3c0f5e00-9369-11e9-8afb-fc3a304970a1.JPG)
.
I tried to run the load script for the sample app (Hospital attendance data) and it worked fine. 

Thanks,
Olive

**Comment by nabeel-oz** [comment]
Hi Olive, 

You seem to have the variable name wrong in the response table. That's probably not the reason for the error though.


Can you replace the load script for the response with the code below and see what fields are returned?

```
Response:
    LOAD
    	*,
    	'$(vCategory)' as Hospital
    Extension PyTools.Prophet(temp{ds, y, args});
```

Also, add `, debug=true` to the args string and see if that gives a clue to the problem.

**Comment by olivesx** [comment]
![image](https://user-images.githubusercontent.com/46431389/59830052-6533ec80-9371-11e9-9fe9-52f66e813ef6.png)
Hi Nabeel, I changed my script accordingly and still getting the same error. for the debug portion, not sure if I have placed it correctly.

**Comment by nabeel-oz** [comment]
Hi Olive, 

I'd comment out the Response table load and the `Drop table temp;` command to check that the load can complete without the SSE call. If it does run successfully, check that the temp table really does have values for each category. For e.g. if there are no PO's for a category the call to Prophet would happen with an empty table.

You've put the debug argument correctly. If you find that this is not a data issue please post the log from the SSE here as well as the message from the Qlik load editor.

**Comment by nabeel-oz** [comment]
Closing this as the issue has been inactive for 2 months

**Comment by felohub** [comment]
Hi Olive and Nabeel.
I also faced this problem and i could solve it (I guess that is the same issue thats Olive refers).

In my case, the issue lays on the data, not on variables.

Even when Qlik response was "Field 'ds' not found", SSE output was "Forecast cannot be generated as the request contains less than two non-Null rows", so the response table never get values on 'ds' field.

I believe that you re using an old file of  _"VIC-Emergency-Department-Attendances.xlsx"_ and you arent loading null values for columns to forecast.

The .py module for prophet forced you to use some null in your data

![image](https://user-images.githubusercontent.com/55557486/74776029-97d21400-5275-11ea-9e2b-aba4e2b99261.png)


In my case, I added more columns with values N/A", and the response was correct.

I hope this helps.

**Comment by abx-212** [comment]
Hello @felohub ,
Hope you are doing well.

How did you add more columns with N/A values?
Doesn't the prophet function only take 2 columns? **date** & **y**


I have added extra months to the date field and passed it to Qlik along with NULL values for the y column, yet, I get the same message: "Forecast cannot be generated as the request contains less than two non-Null rows"

I know this is more than two years late but hopefully you could help.

Thank you
