### ISSUE TITLE
Add my own functions

### ISSUE THREAD

**Issue by Faustiine** [nabeel-oz/qlik-py-tools#36]
Hello, 
Is that possible to add my own function to call them in Qlik ? if Yes I have to modify the _main.py file and the functions.json in which folder and do i have to modify other file or create new one ?

Thank you

:)

**Comment by nabeel-oz** [comment]
Hi @Faustiine , yes you can add your own functions in the `__main__.py` file under the `ExtensionService` class. The function definition that will be visible in Qlik needs to be added under the `functions.json` file. The mapping to tie these bits together is defined in the `functions` property of the `ExtensionService` class.

If you're extending this SSE you can modify the files under the `qlik-py-tools/qlik-py-env/core` folder. If you want to build your own SSE, the examples at [qlik-oss](https://github.com/qlik-oss/server-side-extension) may be a good start.

**Comment by Faustiine** [comment]
Thank you for your answer, I did all of that in the _main.py in the qlik-py-tools-5.1\core , add my function under ExtensionService class, add the id number in the mapping of function and add the function in the json file but when I am in Qlik my new function doesn't appear.
