### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by SyedAlamdar** [nabeel-oz/qlik-py-tools#38]
I actually reinstalled my windows for this. lol. So having two issues when running int.

Issue one (heads up, I already have tried moving back to the older version and tried updating Numpy and HDBSCAN). 
![image](https://user-images.githubusercontent.com/34166232/62180744-edf55f00-b305-11e9-8c46-f61e964042f2.png)

The second issue is for spacy.
![image](https://user-images.githubusercontent.com/34166232/62180841-2f860a00-b306-11e9-8c74-8a1d05e37894.png)

This might be a simple fix for most but I am new to this.

**Comment by nabeel-oz** [comment]
@SyedAlamdar , you shouldn't need to reinstall Windows to get Python working! Can you check that you have the right version of Python installed? It should be the **64 bit** version of Python 3.6.8. 

If you have the 32 bit version, uninstall that and reinstall the 64 bit version.

https://www.python.org/downloads/release/python-368/
Use the `Windows x86-64 executable installer` or `Windows x86-64 web-based installer`.

**Comment by SyedAlamdar** [comment]
There is no emoji that can express what I am feeling right now. It works. Installation process continues. Please mark this closed.
