### ISSUE TITLE
Any plans to Certify this extension by Qlik?

### ISSUE THREAD

**Issue by SyedAlamdar** [nabeel-oz/qlik-py-tools#39]
Hi,

Just wanted to ask if there are plans to certify this extension by Qlik? As an enterprise client, it is hard for me to push for this extension to be incorporated just like other clients who are now trending to adopt Qlik certified extensions only. 

Regards,
Syed

**Comment by nabeel-oz** [comment]
Hi Syed, 

I hadn't given it much thought as I think the process is more relevant to front end components. The certification does apply to any extensions produced by a developer, which I suppose should include Server-Side Extensions, so I'll see if it can be done.

Best regards,
Nabeel
