### ISSUE TITLE
Error when selecting the CHECK Box for dimensions.

### ISSUE THREAD

**Issue by SyedAlamdar** [nabeel-oz/qlik-py-tools#40]
Hi,

Currently, just testing this in the latest desktop version. The visualization with python gives an error when we select a dimension while python is calculating in the background. "Error: Unknown Error". 

Steps to recreate:
1. Select a value from a filter that impacts and triggers the visualization to recompute. 
2. Before the computation is complete, select the green checkbox to confirm the dimension selection. 

That's it. 

Regards

**Comment by nabeel-oz** [comment]
Hi @SyedAlamdar, this is a general behaviour of the SSE protocol and not particular to this extension. Qlik is aborting the previous call, but does not make a new call automatically. Can you re-raise this issue on the SSE repository on Qlik-OSS: https://github.com/qlik-oss/server-side-extension/issues

One workaround for a better user experience is to use a button control that activates or disables the visualisations/ measures using the SSE. The user can then make multiple selections before triggering the SSE call. I've done this in the sample forecasting app.

**Comment by SyedAlamdar** [comment]
https://github.com/qlik-oss/server-side-extension/issues/48

Just added. I'll reach out to our Qlik success manager to also escalate this. Currently not marking this closed to make sure what they say.
