### ISSUE TITLE
Connection Issue while runing Qlik-py-init.bath (Installation)

### ISSUE THREAD

**Issue by lobo55** [nabeel-oz/qlik-py-tools#43]
Hello, i have a issue with the intallation. When i run Qlik-by-Init.batch, i get a Connection Error.
Some adive for my Problem?

![image](https://user-images.githubusercontent.com/54066513/62940811-a924fa00-bdd4-11e9-8749-fb94737df5f5.png)

Thank you and regards

**Comment by nabeel-oz** [comment]
Hi @lobo55 , you need an Internet connection to download the Python packages used in this SSE. If you're trying to install the extension on a device blocked from the Internet you can follow the instructions here: https://github.com/nabeel-oz/qlik-py-tools/tree/master/offline-install

**Comment by lobo55** [comment]
Hi, Thank you. But i have a cnternet conecction and installed Python and MV C++ without any issue.  Maybe the offline version will work, will try it.

**Comment by nabeel-oz** [comment]
Ah, if you do have an Internet connection, the problem may be your proxy settings. There is some help on getting around the issue here: https://stackoverflow.com/questions/30992717/proxy-awareness-with-pip

**Comment by lobo55** [comment]
Thank you, but i tried the offline version now. It works so far, except one error message:

![image](https://user-images.githubusercontent.com/54066513/63018376-f5d20900-be98-11e9-9a72-b24a2fb3cc2a.png)

Thanks for your help

**Comment by nabeel-oz** [comment]
Ah, the joblib package was missing from the offline installation instructions. You'll need to download that as well to the `offline` directory

```
pip download joblib==0.11
```

Are you downloading the packages from a different machine? If not, the connection error you got initially may have been temporary and you could just try running the `Qlik-Py-Init.bat` file again.

If you do need to continue with this offline installation process please use the updated batch file from: https://github.com/nabeel-oz/qlik-py-tools/tree/master/offline-install

**Comment by lobo55** [comment]
Thank you very much, it works fine now.
