### ISSUE TITLE
Can't start Service: ModuleNotFoundError fbprophet

### ISSUE THREAD

**Issue by qlik-user** [nabeel-oz/qlik-py-tools#47]
Hi, after updating the files and setting up a new venv i run into this error.

![errorfbprophet](https://user-images.githubusercontent.com/55279681/64859483-a95e2280-d62a-11e9-9bad-af46d541c9ae.jpg)

I don't know how to handle this.
The ModuleNotFoundError "google" i can solve with downgrading grpcio.
Running this on Windows Server 2012 R2.
I had it successfully running in the past.

Thanks alot!

**Comment by nabeel-oz** [comment]
Hi @qlik-user , what steps did you take to update the SSE?

To upgrade to a new version you'll need to:
- Extract the [new release](qlik-py-env)
- If installing the SSE at the same location as a previous version, delete* the `qlik-py-env` directory.
- Run the `Qlik-Py-Init.bat` file as an administrator

*If you have trained models using the scikit-learn functions, you can take a backup of the `qlik-py-env/models` directory and copy it back after the upgrade. However, you may need to retrain the models if certain packages (`joblib`) have been updated in the release.

**Comment by qlik-user** [comment]
Thanks for your fast response.

I did exactly this, but keep getting this error. :/

**Comment by nabeel-oz** [comment]
Can you try again and get the full log from `Qlik-Py-Init.bat`. There must have been an error around where `pystan` or `fbprophet` are being installed. Also what version of Python are you using?

**Comment by qlik-user** [comment]
Im using Python 3.6.8, like i said, i followed exactly your instructions.
Log init.bat:

`Setting up the Python virtual environment...


Copying project files to the new directory...

C:\QlikSense\PyTools\\generated\ServerSideExtension_pb2.py
C:\QlikSense\PyTools\\generated\__init__.py
2 Datei(en) kopiert
C:\QlikSense\PyTools\\core\functions.json
C:\QlikSense\PyTools\\core\logger.config
C:\QlikSense\PyTools\\core\_clustering.py
C:\QlikSense\PyTools\\core\_common.py
C:\QlikSense\PyTools\\core\_machine_learning.py
C:\QlikSense\PyTools\\core\_prophet.py
C:\QlikSense\PyTools\\core\_sklearn.py
C:\QlikSense\PyTools\\core\_spacy.py
C:\QlikSense\PyTools\\core\_utils.py
C:\QlikSense\PyTools\\core\__init__.py
C:\QlikSense\PyTools\\core\__main__.py
11 Datei(en) kopiert

Activating the virtual environment...

Parameterformat falsch - 850.

Installing required packages...

Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/b2/86/095d2f7829badc207c8
93dd4ac767e871f6cd547145df797ea26baea4e2e/setuptools-41.2.0-py2.py3-none-any.whl

Collecting pip
  Using cached https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cc
e46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl
Installing collected packages: setuptools, pip
  Found existing installation: setuptools 40.6.2
    Uninstalling setuptools-40.6.2:
      Successfully uninstalled setuptools-40.6.2
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-19.2.3 setuptools-41.2.0
Collecting grpcio
  Downloading https://files.pythonhosted.org/packages/9b/03/b18e4402007f11b42aef
ebba56443572faf255b9216e40e3d128c774a48d/grpcio-1.23.0-cp36-cp36m-win_amd64.whl
(1.6MB)
Collecting pystan==2.17
  Using cached https://files.pythonhosted.org/packages/ba/02/a05a0a59f64d32ebb1f
4d7ebff37d6cbcffa9b68ac97395a6b5f3ace3fb4/pystan-2.17.0.0-cp36-cp36m-win_amd64.w
hl
Collecting numpy>=1.7 (from pystan==2.17)
  Using cached https://files.pythonhosted.org/packages/2c/3a/2ffb91f7e310a0aa5ce
a890379291becfc65a915e32ed8d5088bf7544eda/numpy-1.17.2-cp36-cp36m-win_amd64.whl
Collecting Cython!=0.25.1,>=0.22 (from pystan==2.17)
  Downloading https://files.pythonhosted.org/packages/f8/87/a6c730d63512a00cf538
4cdc07dc09cf7285a1f79395afd9956af37a9d1e/Cython-0.29.13-cp36-cp36m-win_amd64.whl
 (1.7MB)
Collecting fbprophet==0.4.post2
  Using cached https://files.pythonhosted.org/packages/9b/a1/fef4ce00acbc28e75c0
d33f60c9777527c4295656903b00ac4c9525cef7f/fbprophet-0.4.post2.tar.gz
Collecting Cython>=0.22 (from fbprophet==0.4.post2)
  Downloading https://files.pythonhosted.org/packages/f8/87/a6c730d63512a00cf538
4cdc07dc09cf7285a1f79395afd9956af37a9d1e/Cython-0.29.13-cp36-cp36m-win_amd64.whl
 (1.7MB)
Collecting scikit-learn==0.20.3
  Using cached https://files.pythonhosted.org/packages/e7/e4/56757c30853899077cf
042f78fb981c0b60f7af4e7a54ca18328b80e0bff/scikit_learn-0.20.3-cp36-cp36m-win_amd
64.whl
Collecting numpy>=1.8.2 (from scikit-learn==0.20.3)
  Using cached https://files.pythonhosted.org/packages/2c/3a/2ffb91f7e310a0aa5ce
a890379291becfc65a915e32ed8d5088bf7544eda/numpy-1.17.2-cp36-cp36m-win_amd64.whl
Collecting scipy>=0.13.3 (from scikit-learn==0.20.3)
  Using cached https://files.pythonhosted.org/packages/e1/63/d919e16c5bd3502a0f7
675f217625bd6f49a412cc1a856aa6b4b5b5b20bc/scipy-1.3.1-cp36-cp36m-win_amd64.whl
Installing collected packages: numpy, scipy, scikit-learn
Successfully installed numpy-1.17.2 scikit-learn-0.20.3 scipy-1.3.1
Collecting hdbscan==0.8.22
Requirement already satisfied: scipy>=0.9 in c:\qliksense\pytools\qlik-py-env\li
b\site-packages (from hdbscan==0.8.22) (1.3.1)
Collecting cython>=0.27 (from hdbscan==0.8.22)
  Downloading https://files.pythonhosted.org/packages/f8/87/a6c730d63512a00cf538
4cdc07dc09cf7285a1f79395afd9956af37a9d1e/Cython-0.29.13-cp36-cp36m-win_amd64.whl
 (1.7MB)
Collecting skater==1.1.2
  Using cached https://files.pythonhosted.org/packages/5a/99/aa0b52e709a621dfae9
fbf8359c9f1ee6d2272e7f53cd2815284e088ec74/skater-1.1.2.tar.gz
Requirement already satisfied: scikit-learn>=0.18 in c:\qliksense\pytools\qlik-p
y-env\lib\site-packages (from skater==1.1.2) (0.20.3)
Collecting scikit-image==0.14 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/28/c1/48848cbd80154d5f3c6
b4f57ee9855c6989ab4b3e841a74c8f38088256cb/scikit_image-0.14.0-cp36-none-win_amd6
4.whl
Collecting pandas>=0.22.0 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/af/b2/51c178d516b85be51f3
a3bd30c654453a3884a34d6329343555418b5d7cb/pandas-0.25.1-cp36-cp36m-win_amd64.whl

Collecting ds-lime>=0.1.1.21 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/ae/b9/b6646f17767c297ed19
7e3bf312434bdc76c8abc6ceef524e85c5fe4a55e/ds-lime-0.1.1.27.tar.gz
Collecting requests (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/51/bd/23c926cd341ea6b7dd0
b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting multiprocess (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/d8/ee/6ea4c86a8416441afa0
27f9aaa40e596bde737bd3a774ed4dce6f0563440/multiprocess-0.70.8-cp36-cp36m-win_amd
64.whl
Collecting dill>=0.2.6 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/39/7a/70803635c850e351257
029089d38748516a280864c97cbc73087afef6d51/dill-0.3.0.tar.gz
Collecting wordcloud==1.3.1 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/be/8b/4e47893d91d2408028b
80815a30f128e840104e5ed10999c0121f5f1a7f3/wordcloud-1.3.1.tar.gz
Collecting joblib==0.11 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/4f/51/870b2ec270fc29c5d89
f85353da420606a9cb39fba4747127e7c7d7eb25d/joblib-0.11-py2.py3-none-any.whl
Collecting Jinja2==2.10 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016
a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting pydotplus==2.0.2 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/60/bf/62567830b700d9f6930
e9ab6831d6ba256f7b0b730acb37278b0ccdffacf/pydotplus-2.0.2.tar.gz
Collecting bs4 (from skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f4561741
39ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Requirement already satisfied: numpy>=1.8.2 in c:\qliksense\pytools\qlik-py-env\
lib\site-packages (from scikit-learn>=0.18->skater==1.1.2) (1.17.2)
Requirement already satisfied: scipy>=0.13.3 in c:\qliksense\pytools\qlik-py-env
\lib\site-packages (from scikit-learn>=0.18->skater==1.1.2) (1.3.1)
Collecting pillow>=4.3.0 (from scikit-image==0.14->skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/4e/d9/468422371e6fcf02d6a
162ee30db4552221de8b2b3ff837363bf54cbb347/Pillow-6.1.0-cp36-cp36m-win_amd64.whl
Collecting PyWavelets>=0.4.0 (from scikit-image==0.14->skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/d9/98/2e0af756fa7c1bb49f7
52078c3e5c1dbf0d98b800c0a9c6f37d7a5cef2ef/PyWavelets-1.0.3-cp36-none-win_amd64.w
hl
Collecting networkx>=1.8 (from scikit-image==0.14->skater==1.1.2)
  Using cached https://files.pythonhosted.org/packages/85/08/f20aef11d4c343b557e
5de6b9548761811eb16e438cee3d32b1c66c8566b/networkx-2.3.zip
Collecting dask[array]>=0.9.0 (from scikit-image==0.14->skater==1.1.2)
  Downloading https://files.pythonhosted.org/packages/63/c2/6b0607f6d6c8028a8ad2
767c550439dfb81e3db42d1b43c172ff9f471861/dask-2.3.0-py3-none-any.whl (763kB)
Collecting spacy==2.1.4
  Using cached https://files.pythonhosted.org/packages/83/26/b829c281ea584cd1d38
89e40b57527782b748cbd91e753796506210f8bb4/spacy-2.1.4-cp36-cp36m-win_amd64.whl
Collecting thinc<7.1.0,>=7.0.2 (from spacy==2.1.4)
  Using cached https://files.pythonhosted.org/packages/b3/36/e3b2463898dc459201f
f3c46dfb7add0f7f300e4bcc7f5823552f7531c80/thinc-7.0.8-cp36-cp36m-win_amd64.whl
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy==2.1.4)
  Using cached https://files.pythonhosted.org/packages/15/8f/0dad3ca706e31258cf7
b9adf40f8d2103444a09dd7d66d46cf6980025c65/murmurhash-1.0.2-cp36-cp36m-win_amd64.
whl
Collecting srsly<1.1.0,>=0.0.5 (from spacy==2.1.4)
  Downloading https://files.pythonhosted.org/packages/e4/11/664f4cf38222cfb71872
4576c16f806f131ef4ad94bf7d8fb9802ecb4a41/srsly-0.1.0-cp36-cp36m-win_amd64.whl (1
71kB)
Collecting efficient_apriori==1.0.0
  Using cached https://files.pythonhosted.org/packages/5b/cb/cd06eb983e4a67d9b12
7df6e3ece87dd7ebea145daa4250929531315bbff/efficient_apriori-1.0.0-py3-none-any.w
hl
Installing collected packages: efficient-apriori
Successfully installed efficient-apriori-1.0.0
C:\QlikSense\PyTools\qlik-py-env\Scripts\python.exe: No module named spacy

Creating a new firewall rule for TCP port 50055...

OK.


All done. Run Qlik-Py-Start.bat to start the SSE Extension Service.

`

**Comment by qlik-user** [comment]
After this I have to install 
grpcio==1.7.3
and
pandas==0.22.0

and after that the error message "fbprophet" appears.

**Comment by nabeel-oz** [comment]
I see an error in the log that mean's the virtual environment is not being activated:

```
Activating the virtual environment...

Parameterformat falsch - 850.
```

Some googling shows that this is a Python issue with German/ Swiss Windows: 
https://github.com/python/cpython/pull/10696?

This is fixed in later versions of Python, but unfortunately those versions are incompatible with some packages used in this SSE. So the solution will be to manually update `activate.bat` with the fix.

So first, just run the initialization up to the point where we create the virtual environment and copy the SSE files:
```
@echo off
echo Setting up the Python virtual environment... & echo.
python -m venv "%~dp0\qlik-py-env"
echo.
echo Copying project files to the new directory... & echo.
xcopy /E /I "%~dp0\generated" "%~dp0\qlik-py-env\generated"
xcopy /E /I "%~dp0\core" "%~dp0\qlik-py-env\core"
echo.
```

Then navigate to `qlik-py-env\Scripts` and update the `activate.bat` file with fix [8321](https://github.com/python/cpython/pull/8321/files). I'm not sure if you'll need the related fix [10295](https://github.com/python/cpython/pull/10295/files) as well.

Then you can run the rest of the script from `Qlik-Py-Init.bat`.

**Comment by nabeel-oz** [comment]
Another option may be to just try the powershell script instead of the batch file, i.e. use `Qlik-Py-Init.ps1`. It sounds like the bug only applies to `activate.bat`. Initializing via powershell uses `activate.ps1` so perhaps won't have this issue.

**Comment by qlik-user** [comment]
> Another option may be to just try the powershell script instead of the batch file, i.e. use `Qlik-Py-Init.ps1`. It sounds like the bug only applies to `activate.bat`. Initializing via powershell uses `activate.ps1` so perhaps won't have this issue.

That just fixed the problem!
I only get the message: "ERRORfbprophetImporting matplotlib failed. Plotting will not work."
But Qlik does the plotting, so thats not a problem.

Thanks alot Nabeel!
