### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by irfanmd2010** [nabeel-oz/qlik-py-tools#48]
Hello , I am getting error "Internal Error" in the screen Emergency attendances forecast "Actual Vs Forecast".

I have followed all the above steps. pls help.

[internal error.docx](https://github.com/nabeel-oz/qlik-py-tools/files/3612930/internal.error.docx)

**Comment by nabeel-oz** [comment]
Hi @irfanmd2010 , that's not enough information to diagnose the issue. I'll need a full log from the SSE terminal to help.

**Comment by nabeel-oz** [comment]
Closing this issue as it has been inactive for more than a month. If you're still having problems, please raise a new issue using the '2 Exception during usage' template.
