### ISSUE TITLE
add_regressor function (fbprophet) in PyTools

### ISSUE THREAD

**Issue by qlik-user** [nabeel-oz/qlik-py-tools#49]
Hi Nabeel,

is it possible to use the add_regressor function of fbprophet in Qlik PyTools?

Best Regards

**Comment by nabeel-oz** [comment]
The Prophet add_regressor function has not been implemented for this SSE yet. However, it is on my list of things to do. I am currently working on the deep-learning branch, but will see if I can include this in the updates too.

**Comment by qlik-user** [comment]
That sounds great. :)
