### ISSUE TITLE
Can't connect to docker

### ISSUE THREAD

**Issue by PhunkyBob** [nabeel-oz/qlik-py-tools#51]
Hello, 

I would like to use this extension, but I don't succeed to make a connection between QlikSense Desktop (June 2019) and the Docker image.

I changed my "settings.ini" file with
`SSEPlugin=PyTools,localhost:50055`

I made 
`docker pull nabeeloz/qlik-py-tools`
and launched it with 
`docker run -p 50055:80 -it nabeeloz/qlik-py-tools`

I have the following output:
```
INFO:matplotlib.font_manager:generated new fontManager
2019-09-24 06:42:51,026 - INFO - Logging enabled
2019-09-24 06:42:51,030 - INFO - *** Running server in insecure mode on port: 50055 ***
```

When I launch QlikSense, I don't see the expected "GetCapabilites" output. There is nothing more in the console.

I tried with different ports without success.

I don't have problem to run others SSE Plugins (like PythonSentiment for instance).

I there a step I missed?

Thank you.

**Comment by nabeel-oz** [comment]
Hi, there are probably two separate issues here.

First being that your settings.ini file will need the IP address of the docker machine.

The second one is the port mapping in the `docker run` command. The log shows your SSE listening on port 50055, so the command should be:

```
docker run -p 50055:50055 -it nabeeloz/qlik-py-tools
```

**Comment by PhunkyBob** [comment]
I was pretty sure I tried all possible combinations of ports, but... you nailed it!

Thank you very much, it works!

And thank you for this awsome plugin.

**Comment by nabeel-oz** [comment]
Cheers!

The port is my fault. The documentation mentions port 80 but the latest docker image listens at 50055. I'll update the documentation.

**Comment by nabeel-oz** [comment]
The documentation has been updated to the correct port. Also a new Docker image for [release 6.0](https://github.com/nabeel-oz/qlik-py-tools//releases/) has been published.
