### ISSUE TITLE
Create future dates for forecast in script

### ISSUE THREAD

**Issue by Franky1010** [nabeel-oz/qlik-py-tools#52]
Hi:

I have a problem. I need to use the forecast in script like example app Sample_App_Forecasting_Simple. My question is if it's possible to create date to forecast in this example, because in the excel that app reads it has the dates to predict already created. So what can I do if I want to crate dates to predict for each hospital and I don't have them created in Excel?

Thanks!

**Comment by nabeel-oz** [comment]
Hi @Franky1010 ,

You can use the Qlik load script to generate dates using the AutoGenerate function. This is commonly used in building the 'Master Calendar' in a Qlik app. 

For the sample app the following code can be used to generate future months. By looping over the Hospital field, we get the correct granularity for this particular data model.

```
// Get the last month for which we have actual data
TempMax:
LOAD
     Max([Month Start]) as MaxActual
RESIDENT Sheet1;

// Set up variables for the start and end forecast month
LET vForecastStart = Peek('MaxActual', 0, 'TempMax');
LET vForecastEnd = AddMonths($(vForecastStart), 6);

Drop table TempMax;

// Add future months for each hospital
FOR EACH vHospital in FieldValueList('Hospital')
	
    // Generate future periods within the range and concatenate to the Sheet1 table
    Concatenate(Sheet1)
    LOAD
    	'$(vHospital)' as Hospital,
        Num(AddMonths($(vForecastStart),IterNo())) as Period,
    	Date(AddMonths($(vForecastStart),IterNo()), 'DD/MM/YY') as [Month Start],
        Null() as Attendances
    AUTOGENERATE(1) 
    WHILE AddMonths($(vForecastStart),IterNo()) <= Date#('$(vForecastEnd)');
	
Next vHospital
```

**Comment by Franky1010** [comment]
Perfect! and when you have created it, in the example of hospitals for example, 
Do we need a minimum of values ​​to be able to make a prediction? 

![image](https://user-images.githubusercontent.com/55097940/65579047-4009d800-df77-11e9-9342-d3c42071c8b0.png)

Because if I put only the second hospital, with seven values, everything works fine. But if I put on the model the first and second hospital we have error:

![image](https://user-images.githubusercontent.com/55097940/65579008-29fc1780-df77-11e9-97cf-fde83133b189.png)

I don't know if thats because we have only two values for the first hospital or what. 

Thanks!

**Comment by Franky1010** [comment]
With three values it works. Is it because the minimum of values for forecast is three right?

**Comment by nabeel-oz** [comment]
Yes, Prophet cannot generate a forecast with less than two non-null rows.

**Comment by Franky1010** [comment]
Okey. Thanks a lot nabeel!!!

**Comment by kutkin54** [comment]
@Franky1010  and @nabeel-oz , how do I prepare the script to include only the forecast with more than two non-null rows  in the LOAD script or chart expression? Can anyone share the script, please?

**Comment by nabeel-oz** [comment]
Hi @kutkin54 , I don't quite understand what you're trying to do. Can you explain further? 

The script to generate additional future periods for the sample app is included in the second comment of this issue above.

**Comment by Franky1010** [comment]
Yes, I understand. What I've done is to prepare another table in script counting how many distinct values I have. If I have three or more I put '1'. If I have less I put '2'. So I only do forectast for '1'. And for '2' I've done the average manually for future dates.

**Comment by nabeel-oz** [comment]
Just note that to get a forecast with a degree of confidence, you will need a lot more than two data points. 

Relevant comments from fbprophet's author here:
https://github.com/facebook/prophet/issues/783
