### ISSUE TITLE
Qlik pytools

### ISSUE THREAD

**Issue by nivi05subhash** [nabeel-oz/qlik-py-tools#53]
Hi Nabeel,
Hope you are doing great

I tried forecasting the data and I am successful in doing the same using the qlik-py-tools, thank you so much introducing this extension

I am in need of some clarifications on this model

1. In this model the data is getting forecasted for history as well as the future years, but I do not want to forecast the data for the past history data rather I wanted to forecast the data only for the future years based on parameter
scenario: Years 2017,2018,2019 and actual data is available for 2017,2018,2019
parameter: 2 years
After the logic the prediction will happen for 5 years  from 2017, 2018,2019,2020,2021 but forecast should happen only for 2020 and 2021 and not for the 2017,2018 and 2019 hope my question is clear
I am trying to modify the logic and implement but I feel some difficulties

Any ideas to do this?

Thank you so much again
Regards
Subash

**Comment by nabeel-oz** [comment]
Hi Subash,

You can add `return=y_then_yhat` to the arguments to get the output you want. This will return actual values for historical data and forecast values for future periods.

More details on the possible parameters are available here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#additional-parameters

Nabeel

**Comment by nivi05subhash** [comment]
Thank you so much Nabeel, that works...
