### ISSUE TITLE
json double quotes error when running Qlik-Py-Start

### ISSUE THREAD

**Issue by hytown** [nabeel-oz/qlik-py-tools#56]
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1254 column 7 (char 31536)
![PyToolsStartError](https://user-images.githubusercontent.com/15326438/66718787-f06c3e80-edb5-11e9-81c6-bb1b322e71e0.jpg)

**Comment by nabeel-oz** [comment]
Hi mate,

Take a look at the last four lines. Have you tried removing the lock file as mentioned at the bottom of your screenshot? 

However, this is an odd error. Did you get the latest release from here: https://github.com/nabeel-oz/qlik-py-tools/releases

**Comment by hytown** [comment]
Thanks Nabeel, I removed the lock file and it works!
