### ISSUE TITLE
logger error

### ISSUE THREAD

**Issue by arulsettu** [nabeel-oz/qlik-py-tools#6]
Hi,
While installing the libraries especially pystan i am getting the error. i installed the Microsoft visual ++ builder tool also

![capture](https://user-images.githubusercontent.com/5644016/45016899-b7ef2280-b043-11e8-80b7-ee8674184373.PNG)

**Comment by nabeel-oz** [comment]
@arulsettu  It seems this issue occurs with the latest version of pystan, i.e. 2.18. You can force pip to install pystan 2.17 by adding the line below to `Qlik-Py-Init.bat`. You should add this before the fbprophet import. 

```
pip install pystan==2.17
```

I'll test the fix in a clean environment before committing the change and publishing a new release.

**Comment by nabeel-oz** [comment]
So upon further investigation, this problem occurs with a combination of using Windows, Python 3.7 and the Visual Studio C++ compiler when importing pystan.  

The solution is to use Python 3.6.6 with the latest release of this SSE (i.e. 3.0). I've published a new release and updated installation notes. 

Something on my to-do list is to build a docker container for this SSE which will help to avoid these kind of issues.

**Comment by arulsettu** [comment]
Awesome it works fine thanks @nabeel-oz
