### ISSUE TITLE
Data Files for Market Basket Analysis App

### ISSUE THREAD

**Issue by aghabdurauf** [nabeel-oz/qlik-py-tools#62]
Dear Nabeel,
Can you provide the data file which you are using in Market Basket Analysis

Thanks & Regards
Agha

**Comment by nabeel-oz** [comment]
Hi Agha,

The link on the first sheet of Sample-App-Market-Basket.qvf will take you to the data source. It's the Online Retail dataset from the UCI Machine Learning Repository: http://archive.ics.uci.edu/ml/datasets/online+retail. You'll just need the Excel file from the Data Folder at that link.

Cheers,
Nabeel
