### ISSUE TITLE
No connection between Python and Qlik

### ISSUE THREAD

**Issue by Tatiana-W2019** [nabeel-oz/qlik-py-tools#63]
Hi Nabeel,
First of all, thanks a lot for your great job! 

Would you please me help with a problem of connection between Python and Qlik. I'd succefully run Qlik-Py-Init.bat (version 6.0) and everything went smoothly. But I still have no connection between Python and Qlik Sense Desktop (Windows10).

P.S. I've already successfully established the connection, but my Qlik did not have the Dashboard extension Bundle installed and I had to reinstall Qlik and did the whole procedure to install SSE again and now I can't establish the connection in any way.   

### 
![file1](https://user-images.githubusercontent.com/57267841/68047447-79103780-fcef-11e9-8f97-9a030dec770d.png)
![file2](https://user-images.githubusercontent.com/57267841/68047449-79103780-fcef-11e9-98f0-9e384a902e83.png)

**Comment by nabeel-oz** [comment]
Hi Tatiana,

Thanks! Hope you find the extension useful once you get it working.

For Qlik Sense Desktop the Settings.ini file can be found in two locations:
`C:/Users/<User ID>/Documents/Qlik/Sense/` and in `C:/Users/AppData/Local/Programs/Qlik/Sense/Engine`.
You may need to update the second file as well with the SSEPlugin settings.

Also just FYI, you can install the Qlik Sense extension bundles through Control Panel > Add Remove Programs even if you skipped them in the initial setup:
![image](https://user-images.githubusercontent.com/21298843/68064041-9c2bfd00-fd6a-11e9-842e-a5fae440502c.png)

**Comment by Tatiana-W2019** [comment]
Nabeel, thanks a lot, it works!
