### ISSUE TITLE
Error on loading my new QS App

### ISSUE THREAD

**Issue by aghabdurauf** [nabeel-oz/qlik-py-tools#64]
**Association_Rules**

**Describe the bug**
While using the new app this error occurs in Qlik Sense

> 'PyTools.Association_Rules' is not a registered SSE function. Ensure the plugin is running and try restarting Qlik Engine..

**Error message in Qlik**
Provide a screenshot of the error message in Qlik.
![Error Qlik SSE Restart](https://user-images.githubusercontent.com/18259823/68101075-9f9bc180-feed-11e9-828c-6c658b9ec1ac.PNG)
![Error SSE Script](https://user-images.githubusercontent.com/18259823/68101958-3d918b00-fef2-11e9-812c-75752fe3bd08.PNG)

**Environment:**
 - Windows 10
 - Qlik Sense Desktop

**Additional context**
Whenever I load my new app this error message occurs. I also restart SSE engine and all of things, but there the same error is occurring.

**Comment by nabeel-oz** [comment]
The error message means that Qlik has not detected the Server-Side Extension. Make sure you have the SSE running in a terminal (for e.g using `Qlik-Py-Start.bat`), and also that you have set up the Settings.ini file as described in the installation guide. This might be a similar problem to issue #63.

**Comment by aghabdurauf** [comment]
I have done all the things that you have mention in documentation. I also run 

> Qlik-Py-Start.bat as Run as Administrator but same error occurs.

**Comment by aghabdurauf** [comment]
![Error SSE Script 2](https://user-images.githubusercontent.com/18259823/68114876-e94dd180-ff18-11e9-9c73-1578cfea74fc.PNG)
![Settings](https://user-images.githubusercontent.com/18259823/68114887-ef43b280-ff18-11e9-9540-4c32c7bad4ca.PNG)

**Comment by nabeel-oz** [comment]
When you say that the sample apps are running, do you mean that the SSE functions are being executed correctly? For e.g. with the clustering app?

Could you be using an older release of the SSE which does not have the Association_Rules function? Take a look at the functions listed in the SSE terminal and see if Association_Rules capability appears in there.

**Comment by aghabdurauf** [comment]
it's not appearing

**Comment by aghabdurauf** [comment]
But LOTR App is working properly

**Comment by aghabdurauf** [comment]
![SSE Update git](https://user-images.githubusercontent.com/18259823/68119657-1607e600-ff25-11e9-9e56-594d3df67c09.PNG)
I have installed this file downloaded from Github

**Comment by nabeel-oz** [comment]
> it's not appearing

If the AssociationRules function is not in the list of capabilities shown in the terminal, you are using outdated source files.

> But LOTR App is working properly

That app is setup to reload using QVDs and doesn't require the SSE unless you change certain variables in the load script. 

> I have installed this file downloaded from Github

You'll need to get the zip file for the latest release from here: https://github.com/nabeel-oz/qlik-py-tools/releases. Then follow the [installation guide](https://github.com/nabeel-oz/qlik-py-tools#installation) again from step 3 onward.
