### ISSUE TITLE
Numpy Error During the Load of HR Sample App

### ISSUE THREAD

**Issue by aghabdurauf** [nabeel-oz/qlik-py-tools#65]
**Sklearn**

**When I load Sample Train & Test App of HR Attrition the following error occurred, but it was running on 5.0 Version**

**Connector reply error: grpc::StatusCode::UNKNOWN: 'Exception iterating responses: 'numpy.ndarray' object has no attribute 'values''**

**Error message in Qlik**
![Numpy Error on Predict Data](https://user-images.githubusercontent.com/18259823/68307360-ec89be80-00cc-11ea-8c7b-14b5c4132822.PNG)
![CLI Numpy Error](https://user-images.githubusercontent.com/18259823/68308769-3d021b80-00cf-11ea-9c05-63d5d13fcb18.PNG)

**Environment:**
 - Windows 10
 - Qlik Sense Desktop
 - SSE Version 6.0

**Comment by nabeel-oz** [comment]
Thanks for reporting. This is a bug which I'll investigate. The bug does not effect the K-fold Cross Validation app so for now you can use that to train the model.
