### ISSUE TITLE
Installation issue with HDBScan and Spacy

### ISSUE THREAD

**Issue by shiwaniers** [nabeel-oz/qlik-py-tools#68]
I experience a bug while setting up the SSE (Qlik-Py-init) on a Windows Server. The packages HDBScan and Spacey result in error code 1. When I run the same file on Desktop, it does work. 

**Screenshots**
If applicable, add screenshots from `Qlik-Py-Init` to show the full error message.
![image](https://user-images.githubusercontent.com/45182285/68586176-59fa6e00-0484-11ea-9b89-9e86512c09af.png)
![image](https://user-images.githubusercontent.com/45182285/68586206-6d0d3e00-0484-11ea-92f5-c288926e25fa.png)
![image](https://user-images.githubusercontent.com/45182285/68586346-c7a69a00-0484-11ea-816c-127de4177ff9.png)

**Environment:**
 - OS: Windows Server
 - Qlik Sense Enterprise
 - SSE Version: v.6.2.
-  Python 3.6.8
-  Visual Studio C++

**Comment by nabeel-oz** [comment]
Please refer to issue #45. It looks like you have the 32 bit version of Python installed on your Windows Server machine. You'll need to uninstall it and install the 64 bit version.

**Comment by shiwaniers** [comment]
Hi Nabeel, thanks for your quick reply! It indeed helped to install Spacy and HDBScan. However, by using the x64 version instead of the x32 fbprophet is not installing anymore, while it did work initially with the x32 version. I saw recent issues involving the lack of Visual Studio C++ Tools, but I have those tools installed.

Do you have an idea what the cause of this problem could be?

![image](https://user-images.githubusercontent.com/45182285/68684380-ac14bf80-0568-11ea-9397-e35f73f5ad40.png)

**Comment by nabeel-oz** [comment]
The error does seem related to your Build Tools installation as it fails when fbprophet tries to build a pystan model, which in turn relies on a C++ compiler. 

Try updating your VS Build Tools installation and make sure you have C++ compilers for ARM64 selected. You may have selected the 32 bit option here as well.

![image](https://user-images.githubusercontent.com/21298843/68716991-a915df80-05f9-11ea-81e7-ca35fe8f4124.png)

Then you'll need to delete the `qlik-py-env` directory and run the initialization for the SSE again.

**Comment by Apostolis12** [comment]
Thank you for your response

**Comment by shiwaniers** [comment]
Thanks for your reply.

**Comment by Apostolis12** [comment]
Hi Nabeel,

First of all, thank you for the excellent help.
Do you kown  why the entity is not highlighted?

Thank you
Best Regards
Apostolos

[image: image.png]

**Comment by nabeel-oz** [comment]
Hi Apostolos, 

Your image didn't show up. Perhaps add it to your other open issues so that it is easier to track.

Cheers,
Nabeel

**Comment by Apostolis12** [comment]
Στις Παρ, 22 Νοε 2019 στις 11:33 π.μ., ο/η Nabeel <notifications@github.com>
έγραψε:

**Comment by Apostolis12** [comment]
Hi Nabeel,

First of all, thank you for the excellent help.
Do you kown  why the selected entity in text is not highlighted?

Thank you
Best Regards
Apostolos

**Comment by Apostolis12** [comment]
HI Nabeel,

In  Association Rules Call Function I got the following error:

Connector reply error: grpc::StatusCode::RESOURCE_EXHAUSTED: 'Sent message
larger than max (69292024 vs. 10485760)': [Association Rules]: LOAD rule as
[Association Rule], rule_lhs as [Entities LHS], rule_rhs as [Entities RHS],
support as Support, confidence as Confidence, lift as Lift EXTENSION
PyTools.Association_Rules(Entities{para, item, args})

Can you help me?

Thank you in advance

**Comment by nabeel-oz** [comment]
Hi @Apostolis12,

You've hit the maximum limit for a single message which is set under `__main__.py` line 40:
```
# Set the maximum message length for gRPC in bytes
MAX_MESSAGE_LENGTH = 10 * 1024 * 1024
```

However, instead of changing this limit, I'd first consider how your response got so large for a single bundle. The SSE breaks up the response into multiple bundles and a single bundle should usually not exceed the limit.

In the case of association rules, if you're getting a huge number of rules back, it may be because you have set the `min_support` too low and are getting back associations which aren't going to be very useful.

Note that this is a closed issue and unrelated to this problem. So please raise a new issue if needed.

**Comment by Apostolis12** [comment]
thank you for the response

Στις Τρί, 3 Δεκ 2019 στις 6:11 π.μ., ο/η Nabeel <notifications@github.com>
έγραψε:

**Comment by Apostolis12** [comment]
Hi Nabeel and Happy New year. I hope the disasters in Australia soon stop.

 I am retraining the English text with named labels to excel file  and the
model responds very well.
I am doing the same process to the Greek text but the model not responds.

Is there something I haven't thought?

Thank you very much

Your help is greatly appreciated

Apostolos

**Comment by nabeel-oz** [comment]
Hi Apostolos, 

Happy new year! Thanks, we're all hoping there is some reprieve for the regional communities and fire fighters soon.

The default options use the English model for retraining. If you want to retrain the Greek model you'll need to specify it as the `base_model` in the additional arguments.

```
'base_model=el_core_news_sm, epochs=100, drop=0.25, test=0.3'
```

Nabeel
