### ISSUE TITLE
SKLearnForQlik 

### ISSUE THREAD

**Issue by Apostolis12** [nabeel-oz/qlik-py-tools#71]
The PyTools Server not Started. I remarked the SKLearnForQlik  in __main
__.py and  the Server is running
import numpy as np
import pandas as pd
from pandas.api.types import is_string_dtype
from pandas.api.types import is_numeric_dtype
import _utils as utils
from _prophet import ProphetForQlik
from _clustering import HDBSCANForQlik
#from _sklearn import SKLearnForQlik
from _spacy import SpaCyForQlik
from _common import CommonFunction
**Screenshots**
![Running Server](https://user-images.githubusercontent.com/5312206/68767503-71269080-0629-11ea-89be-2cb13b90b7da.png)

**Environment:**
 - Windows 2016
 - Qlik Sense
 - SSE Version

**Additional context**

thank you very much

**Comment by nabeel-oz** [comment]
Hi @Apostolis12 , the solution for this is the same as issue #70. Please take a look at my response there.

**Comment by nabeel-oz** [comment]
Closing this issue as a solution has been provided.
