### ISSUE TITLE
Available pretrained statistical models for Greek

### ISSUE THREAD

**Issue by Apostolis12** [nabeel-oz/qlik-py-tools#72]
Hi  Nabeel,
 el_core_news_md

**Describe the bug**
python -m spacy download el_core_news_sm
python -m spacy download el_core_news_md

I have installed  the spacy greek module  adding the above lines in Init.bat and

**Error message in Qlik**
![qlik sense error](https://user-images.githubusercontent.com/5312206/68774535-ee580280-0635-11ea-872d-a17316ca3ea2.png)

During load data debugging is appearing the errror "16:40:44 A
Field 'el_core_news_md' not found"

**Environment:**
 - Windows Server 2016
 - Qlik Sense 
 - SSE Version

Thank you very much

**Comment by nabeel-oz** [comment]
Hi @Apostolis12 ,

To use the Greek model you will need to specify the model name using the `spaCy_Get_Entities_From_Model` function.

```
// Set up a temporary table that will be used as input to the SSE
[TextEntity:
LOAD
    ParagraphID as key,
    ParagraphText as text,
    'el_core_news_md' as model_name,
    'debug=false' as args   
RESIDENT ParagraphsText;

// Use the LOAD...EXTENSION syntax to call the spaCy_Get_Entities_From_Model function
[Named EntitiesText]:
LOAD 
    key as TextParagraphID,
    entity as [TextEntity v1],
    type as [TextEntity Type v1],
    description as [Entity Description v2]
EXTENSION PyTools.spaCy_Get_Entities_From_Model(Texts{key, text, model_name, args});
```

The documentation wasn't so clear on this so I've updated it [here](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/NER.md#ner-with-a-specified-model).

However, it is odd that the error message says **field** not found, which is purely a Qlik load script error. Might be worth checking if there is an issue the load script as well where el_core_news_md is being considered a field name.

**Comment by Apostolis12** [comment]
Thank you for the response

Στις Πέμ, 14 Νοε 2019 στις 4:12 π.μ., ο/η Nabeel <notifications@github.com>
έγραψε:
