### ISSUE TITLE
No communication between PyTools and Qlik

### ISSUE THREAD

**Issue by jfdierckx** [nabeel-oz/qlik-py-tools#75]
I'm trying to use both PyTools and R SSE with my Qlik Sense Desktop.

I've done the installation of PyTools according to the documentation, the service seems to be starting fine, as it says : 

2019-11-29 04:53:44,524 - INFO - Logging enabled
2019-11-29 04:53:44,535 - INFO - *** Running server in insecure mode on port: 50055 ***

I've created the Settings.ini file for Qlik Sense Desktop : 

[Settings 7]
EnableSSEgRPC=1
SSEPlugin=R,localhost:50051;PyTools,localhost:50055

However, when I try to use PyTools in Qlik Sense, nothing happens. If I type PyTools. in the expression builder, it does not propose any function. And none of the Python examples seem to work.

My R SSE engine works perfectly fine though, and if I look at the SSE_Engine_2019-11-29.log, there are only calls to the R engine, and none to the Python engine...

I tried to replace my installation of PyTools by the Docker version, but the behaviour is exactly the same...

I also tried to restart Qlik Sense Desktop several times, but it didn't change anything.

JF.

**Comment by nabeel-oz** [comment]
For Qlik Sense Desktop the Settings.ini file can be found in two locations:

`C:/Users/<User ID>/Documents/Qlik/Sense/` and 
`C:/Users/AppData/Local/Programs/Qlik/Sense/Engine`.

You may need to update the second file as well with the SSEPlugin settings.

Also, you don't need the `EnableSSEgRPC=1` line with a recent version of Qlik Sense. It's probably harmless, but I'd try removing that as well if the solution above doesn't work.

Cheers,
Nabeel

**Comment by jfdierckx** [comment]
Yes, this solved the issue ! Thanks a million for your quick response !!!

I think it would be good to mention those both folders in the documentation.

**Comment by nabeel-oz** [comment]
Great! I've updated the documentation as you suggested.

**Comment by mk1192** [comment]
Hi @nabeel-oz .. I am trying to config the setup using the docker image. I see the same issue the capabilities are not starting after the server initiation. 

I am using the latest Qlik Desktop version May 2024, and I am not able to see the second folder to update the Settings.ini file. Is there is any update to this?
