### ISSUE TITLE
issue when trying to start the service

### ISSUE THREAD

**Issue by alec1982** [nabeel-oz/qlik-py-tools#76]
getting an error..anyone can help, error below. No logs generated on core folder

File "C:\Users\bharfoush\Envs\qlik-py-env\lib\site-packages\efficient_apriori\apriori.py", line 9, in <module>
    from efficient_apriori.rules import generate_rules_apriori
  File "C:\Users\bharfoush\Envs\qlik-py-env\lib\site-packages\efficient_apriori\rules.py", line 203
    yielded: set = set()
           ^
SyntaxError: invalid syntax

**Comment by nabeel-oz** [comment]
Hi @alec1982 , can you please use the issue template and provide more context. This error message is pointing to a package that works fine in my testing and for other users.

**Comment by nabeel-oz** [comment]
Just taking another look at that bit of code, it is using annotations which were only introduced in Python 3.6. So this package may have issues with Python 3.5 and below. 

The recommended version for this SSE is Python 3.6.8.

**Comment by alec1982** [comment]
Thank you. Yes, I use 3.5. I will go ahead and upgrade tonight and test. Thxs for your quick response.

**Comment by alec1982** [comment]
thanks again Nabeel. I installed 3.6 and passed that error but then I run into another one which is showing in the new attached. screenshot.
<img width="661" alt="Capture" src="https://user-images.githubusercontent.com/17154532/70284438-fc5ef600-1791-11ea-80c1-074446991ca9.PNG">

the error:
ERROR - Exception iterating responses: [Errno 2] No such file or directory: '..\\models\\HR-Attrition-LR.joblib'

**Comment by nabeel-oz** [comment]
Are you trying to use the HR Attrition Prediction app? That app requires a trained machine learning model. You can generate the model by reloading the K-Fold Cross Validation app first. Also, take a look at the other app dependencies mentioned here: https://github.com/nabeel-oz/qlik-py-tools#usage

**Comment by jinzanzan** [comment]
I used the python environment of 3.7.3, but it was the same error. May I ask how to solve it

**Comment by nabeel-oz** [comment]
@jinzanzan , this SSE requires Python 3.6 as some of the packages do not support version 3.7. Take a look at the [Pre-requisites](https://github.com/nabeel-oz/qlik-py-tools#pre-requisites). The other option is to use the [Docker image](https://github.com/nabeel-oz/qlik-py-tools#docker-image) which has it's own self-contained environment.

**Comment by nabeel-oz** [comment]
Closing this issue as an explanation has been provided.
