### ISSUE TITLE
Error for marketbasket

### ISSUE THREAD

**Issue by MikkoParkkila** [nabeel-oz/qlik-py-tools#79]
Hi

I get this error message when running data through the model. Nothing else has been changed execpt the underlaying data and min_support value.

> 2019-12-17 12:06:36,875 - ERROR - Exception iterating responses: bad operand type for unary +: 'str'
> Traceback (most recent call last):
>   File "C:\Users\User\Desktop\QVsense\qlik-py-tools-master\qlik-py-env\lib\site-packages\grpc\_server.py", line 453, in _take_response_from_response_iterator
>     return next(response_iterator), True
>   File "__main__.py", line 701, in _misc
>     response = handle.association_rules()
>   File "C:\Users\User\Desktop\QVsense\qlik-py-tools-master\qlik-py-env\core\_common.py", line 75, in association_rules
>     + "the min_support and min_confidence parameters.\ne.g. by passing min_support=0.2|float in the arguments."
> TypeError: bad operand type for unary +: 'str'

**Comment by MikkoParkkila** [comment]
This is what it returns in Qlik Sense

The following error occurred:
Connector reply error: grpc::StatusCode::UNKNOWN: 'Exception iterating responses: bad operand type for unary +: 'str''

**Comment by nabeel-oz** [comment]
This is an error in the error message! I'll add a fix for this in the next release.

The message should be telling you this:

**No association rules could be found. You may get results by lowering the limits imposed by the min_support and min_confidence parameters. e.g. by passing min_support=0.2|float in the arguments.**

So you can try using lower values for `min_support` and/or `min_confidence`  until you start getting results. 

In case the parameters are confusing, this [KDnuggets article](https://www.kdnuggets.com/2016/04/association-rules-apriori-algorithm-tutorial.html) provides a nice explanation.

**Comment by MikkoParkkila** [comment]
Yes noticed the same when opened the common.py file that it's only string error. Would be nice for a neebie like me to have the min_confidence as an example on the sample QS file as commented line, but got it to run after few trial and error, let's see if it pushes anything out from the pipe this time.
