### ISSUE TITLE
Multiple Errors Running Qlik-Py-Init

### ISSUE THREAD

**Issue by jasandi** [nabeel-oz/qlik-py-tools#81]
**Describe the bug**
I'm trying to get the SSE server running. When I run the Qlik-Py-Init file, I am getting the following errors.

**Screenshots Qlik-Py-Init**
![Qlik-Py-Init_Error 1](https://user-images.githubusercontent.com/47084203/71318697-823baa80-24cf-11ea-8784-a036e2600ba1.PNG)
![Qlik-Py-Init_Error 2](https://user-images.githubusercontent.com/47084203/71318698-823baa80-24cf-11ea-9ea2-079bbd32b442.PNG)
![Qlik-Py-Init_Error 3](https://user-images.githubusercontent.com/47084203/71318699-823baa80-24cf-11ea-93c5-5862da1c53fc.PNG)

**Screenshots Qlik-Py-Start**
![Qlik-Py-Start_Error](https://user-images.githubusercontent.com/47084203/71318700-82d44100-24cf-11ea-9ad4-0c5dfe5d7bc4.PNG)

**Environment:**
 - Windows 10
 - Qlik Sense Desktop
 - SSE Version 6.2
- Python 3.6.0

**Additional context**
I have deleted the qlik-py-env folder multiple times and restarted the process without any success.

**Comment by nabeel-oz** [comment]
Hi @jasandi , All the errors are occurring during the use of the C++ compilers that need to installed using the Visual Studio Build Tools. So it looks like there was an error with that installation.

I've described the steps to check the Build Tools installation here:
https://github.com/nabeel-oz/qlik-py-tools/issues/73#issuecomment-562053765

**Comment by jasandi** [comment]
Hi @nabeel-oz,
thanks for your help. I figured out that I had installed Windows 10 SDK (10.0.17763.0) instead of Windows 10 SDK (10.0.17134.0). The reconfiguration solved my issue.
