### ISSUE TITLE
synchronize request

### ISSUE THREAD

**Issue by MarcoBIConsultant** [nabeel-oz/qlik-py-tools#88]
Hi,
I have a problem when execute the PyTools several times in same time. For some functions performed in parallel it return nothing data. I think there is a problem with synchronize the request of tools.

Marco

**Comment by nabeel-oz** [comment]
Hi Marco, please follow the issue template to provide enough information to investigate. Also, what is the behaviour in Qlik? Are the users taking any actions while waiting for the SSE to respond? What do the SSE logs show?

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz,
In the qlik application the chart says: 
"Selections didn't generate data for this chart"

In the python logs:

"Forecast cannot be generated as the request contains less than two non-Null rows"

and the file log compare when the function run there is:

The message when function run:  "Make future data frame parameters: {'periods': 24, 'freq': 'MS'}"
The message when function doesn't run: "Make future data frame parameters: {'periods': 0, 'freq': 'MS'}"

In the SSE logs:

"WARN	SERVERQLIK	SSE.Engine.Engine	24    R#22 grpc::StatusCode::CANCELLED: 'Cancelled'"

It is strange because when i run the only chart with this function it runs but if i run multiple function in a qlik sheet it doesn't run with the same function in other chart runs.
The function is prophet facebook.

Is there a problem with synchronize?

Thank you
Marco

**Comment by nabeel-oz** [comment]
No this doesn't look like a synchronisation issue.

In the case with zero future periods it just means that the function did not receive any future periods from Qlik and so will not generate a forecast. This can happen if the future periods are not available for certain dimensions and a user makes selections in those dimensions. The usage doc covers a technique to build a forecast calendar to solve this data modelling problem.

The cancelled message might indicate that the user took an action that cancelled the function call. Even clicking on the green tick mark that confirms a selection interrupts a SSE call. That is why the sample app make use of variables and buttons to allow the user to make all their selections and then trigger the function call.

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz ,
Thank you for rapid answer.
The issue isn't always in this chart . If i put only this chart in a qlik sheet it run.
If i put this chart in a sheet with another chart, where use prophet facebook function, it doesn't run and it says that message.
Why?

Thank you

Marco

**Comment by nabeel-oz** [comment]
Hi Marco,

Having other charts and expressions on the sheet does not interfere with the SSE calls other than giving the Qlik engine more work to do.

You can test this by using the `Parallel SSE Calls` sheet in the app attached below. This sheet makes 7 unique calls to the Prophet function in PyTools. It also has 5 standard expressions in the charts. I have tested this app without issue, even with multiple users generating unique calls using different values for the trend fitting slider. 

[Sample_App_Forecasting_Simple (issue #88).zip](https://github.com/nabeel-oz/qlik-py-tools/files/4120375/Sample_App_Forecasting_Simple.issue.88.zip)

I still think the clue you need is in my previous response. You should visualize the dimension and measure you are using as input to Prophet in a table and check for issues, for e.g. missing future periods, which may only occur when certain selections are made.

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz ,
i have a test and now it runs.

Thank you

Marco
