### ISSUE TITLE
Issue execute start script version 6.4

### ISSUE THREAD

**Issue by MarcoBIConsultant** [nabeel-oz/qlik-py-tools#89]
Hi,
I have a problem after installation package version 6.4.
I run start batch script but it returns this message:

![immagine](https://user-images.githubusercontent.com/48477504/73268265-f5c18d80-41da-11ea-9eb1-85df2c15a04e.png)

Thank you

**Comment by nabeel-oz** [comment]
This looks like an issue with `fbprophet` as discussed [here](https://github.com/dr-prodigy/python-holidays/issues/277). If you installed the SSE on or after 26 Jan 2020 you may have this issue.

I'll address this in the next release, but for now you can fix your existing installation with these steps:

- Open a powershell window at `..\qlik-py-env\Scripts`
- Run this command to activate the Python virtual environment: `.\activate.ps1`
- Downgrade `holidays` to the previous compatible version for `fbprophet`: 

   ```
   pip install --upgrade holidays==0.9.11
   ```
- Restart PyTools using the `Qlik-Py-Start` bat or ps1 file
