### ISSUE TITLE
Sample_App_Forecasting_Simple: Tab Forecast Lines disappear when drilling for a year

### ISSUE THREAD

**Issue by njsouthern** [nabeel-oz/qlik-py-tools#91]
Hi Nabeel, thank you for sharing your work it is very impressive.

Re-edited this I believe is similar to 
Facebook prophet forecasting not working for filters #27

TAB
Emergency Attendances Forecast
my initial question was :
The chart is dynamic if you drill on hospital, why if you drill into 2018 do we lose the Upper and Lower limit forecast lines ? 

I wish to present the upper and lower limits for full data set or subset ie filtered, what is best approach to take? to make the chart more dynamic/Qlik like?

**Comment by nabeel-oz** [comment]
Hi @njsouthern , thanks! 

To answer your question, Prophet won't generate a forecast if the selections don't contain any future periods. For the Emergency Attendances app the future periods are in 2019, so selecting 2018 will just show you actual figures.

The solution does allow for predictions to be generated on any subset of data. You can see this in [Sample_App_Prophet.qvf](https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Sample_App_Prophet.qvf) app which uses the data modelling technique described here: https://github.com/nabeel-oz/qlik-py-tools/blob/master/docs/Prophet.md#use-prophet-with-your-own-app
