### ISSUE TITLE
Timestamps in the log are note correct

### ISSUE THREAD

**Issue by hammamr** [nabeel-oz/qlik-py-tools#94]
Hello,

I'm running the extension in docker container lacally on windows 10 using docker desktop for windows and QlikSense desktop..

I used the following command to run the container:
`docker run -p 50055:50055 -d --restart unless-stopped -v pytools-models:/qlik-py-tools/models -v ~/Documents/logs:/qlik-py-tools/core/logs nabeeloz/qlik-py-tools`

I have an issue with timestamps in the log SSEPlugin.log.
I have just opened an application that uses prophet, today at 10H46.
The log file has been modified 04 mars at 10H46 but the content of the log file is showing 29 Feb 7H27 (see attached print screen).

Is that normal?

Is it possible to have a log file per day with the day date in the name of the log file?
Otherwise, how to see the content of the directory containing the models in my case ?

![image](https://user-images.githubusercontent.com/41787890/75868102-e2bc6180-5e07-11ea-8d38-676ddec2d5be.png)

Best regards.
Sidi

**Comment by hammamr** [comment]
Hello,

It seems that it is a bug of docker desktop for windows: [](https://github.com/docker/for-win/issues/3168)

This two questions are always valid:

Is it possible to have a log file per day with the day date in the name of the log file?
Otherwise, how to see the content of the directory containing the models in my case ?

Best regards.
Sidi

**Comment by nabeel-oz** [comment]
Hi Sidi,

> Is it possible to have a log file per day with the day date in the name of the log file?

The SSEPlugin.log file does get archived, so you should start to see additional logs with timestamps after using the SSE over different dates. The latest log file is always named SSEPlugin.log.

> Otherwise, how to see the content of the directory containing the models in my case ?

In the `docker run` command you specified a docker volume to store your models. I'm not sure where that gets stored in Docker for Windows. However, you could simply use a directory for the models instead of the volume as you've done for the logs, for example to `Documents/models`:
```
docker run -p 50055:50055 -d --restart unless-stopped -v ~/Documents/models:/qlik-py-tools/models -v ~/Documents/logs:/qlik-py-tools/core/logs nabeeloz/qlik-py-tools
```

**Comment by hammamr** [comment]
Hi Nabeel,

> The SSEPlugin.log file does get archived, so you should start to see additional logs with timestamps after using the SSE over different dates. The latest log file is always named SSEPlugin.log.

This feature is not working for me with docker desktop for windows 10 running locally on my computer.

> In the docker run command you specified a docker volume to store your models. I'm not sure where that gets stored in Docker for Windows. However, you could simply use a directory for the models instead of the volume as you've done for the logs, for example to Documents/models:

Finally I found how to access to the folder models:

```
PS C:\Users\isou0740> docker exec -it 65b ls -lrt /qlik-py-tools/
total 36
drwxrwxrwx 2 root root  4096 Oct 28  2018 models
-rwxrwxrwx 1 root root 20090 Oct 29  2018 feature_importance.py
-rwxrwxrwx 1 root root  1353 Feb 12 02:41 Dockerfile
drwxrwxrwx 1 root root  4096 Feb 29 03:56 generated
drwxrwxrwx 1 root root  4096 Feb 29 03:56 core
PS C:\Users\isou0740>
```
