### ISSUE TITLE
'Series' object has no attribute 'nonzero'

### ISSUE THREAD

**Issue by tauceef** [nabeel-oz/qlik-py-tools#95]
**Function**
Pytools.Prophet

**Describe the bug**
I have created virtual environment in Anaconda and installed all the required packages as per init file. After that I am able to start the project as well and when I start QlikSense desktop it shows adding all the capabilities. Issue is when I open any of the apps like Forecasting and other I am getting few errors like "'Series' object has no attribute 'nonzero'" in the Forecasting app and " No such file or directory: '..\\models\\NoShow-RF.joblib'" while using ML Predictions app.

**Full error message from Python**
Provide full stack trace for the error.
If using `Qlik-Py-Start` you can provide screenshots from the terminal. Make sure to go all the way up to the start of the errors.
Alternatively, you can provide the latest log files from `../qlik-py-tools/qlik-py-env/core/logs`.
[SSEPlugin.log](https://github.com/nabeel-oz/qlik-py-tools/files/4343855/SSEPlugin.log)

**Error message in Qlik**
Charts showing "Unknown Error"

**Expression or load script used in Qlik**
Pytools.Prophet([Month Start], Sum(Attendances), 'freq=M')

**Environment:**
 - OS [Windows 10]
 - Qlik Sense Desktop
 - SSE Version 7.0

**Additional context**
Looking forward for your response.

Regards,
Tauceef

**Comment by nabeel-oz** [comment]
Hi @tauceef ,

The first problem may be that you are using Anaconda. This extension is tested with vanilla Python 3.6 and does not support Anaconda. The initialization script sets up a Python virtual environment that is known to work with this Server Side Extension.

I don't have any reference to the `nonzero` attribute in the code, so I can't give any explanation to the error you're getting without a stack trace. The problem with the ML Predictions app just looks like the model may not exist. You will need to run the K-fold Cross Validation app to train the model. Take a look at the app dependencies under the [Usage](https://github.com/nabeel-oz/qlik-py-tools#usage) section.

I do strongly recommend using the `Qlik-Py-Init` script or the Docker container to setup the SSE.

**Comment by tauceef** [comment]
Thanks Nabeel,
Its working now.
