### ISSUE TITLE
Error installation qlik tools 7.1: missing wheel package

### ISSUE THREAD

**Issue by MarcoBIConsultant** [nabeel-oz/qlik-py-tools#98]
Hi, I have a issue in the qlik tools 7.1 installation.
The errors is missing wheel package.

![immagine](https://user-images.githubusercontent.com/48477504/81927901-b6ca1300-95e4-11ea-8c65-e6de9ab0b299.png)

Thank you

**Comment by nabeel-oz** [comment]
Hi Marco, this looks like a change with pip 20.1. The wheel package did not need to be explicitly installed previously.

Thanks for raising this issue. I have just published a new release with a fix:
https://github.com/nabeel-oz/qlik-py-tools/releases

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz ,
i try new release but the issue not change.

![immagine](https://user-images.githubusercontent.com/48477504/82021778-c18bb300-968b-11ea-9c36-5898a324bba4.png)

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz, the qlik-py-tools-7.2.zip is run but the Source code (zip)  not run in the release 7.2

**Comment by nabeel-oz** [comment]
Hi @MarcoBIConsultant, yes apologies I just updated the initialization scripts in the release files. I haven't pushed the changes to the source code yet as they've gone into another branch that I want to merge soon.

**Comment by MarcoBIConsultant** [comment]
Hi @nabeel-oz  dont worry. Thank you for all.
